CREATE OR REPLACE VIEW core.CARRIER_DECISION_EXPLANATION AS
SELECT
    DECISION_ID,
    CLIENT_ID,
    ENTITY_ID AS CONTAINER_ID,
    RULE_ID,
    RULE_NAME,
    MATCHED,
    DECISION,
    REASON,
    DETAIL,
    CREATED_DSTAMP
FROM audit.RULE_DECISION_LOG
WHERE ENGINE_NAME='CARRIER_SELECTION'
  AND ENTITY_TYPE='ORDER_CONTAINER';
