CREATE OR REPLACE VIEW core.CARRIER_SELECTION_WORKBENCH AS
SELECT
    oc.CLIENT_ID,
    oc.ORDER_ID,
    oc.CONTAINER_ID,
    oc.STATUS AS CONTAINER_STATUS,
    oc.DELIVERY_CLASS,
    oc.WEIGHT,
    oc.VOLUME,
    oh.ORDER_VALUE,
    oh.DISPATCH_METHOD,
    oh.SERVICE_LEVEL AS REQUESTED_SERVICE_LEVEL,
    oh.POSTCODE,
    oh.COUNTRY,
    oc.CARRIER_ID,
    oc.SERVICE_LEVEL AS SELECTED_SERVICE_LEVEL,
    oc.CARRIER_COST,
    oc.CARRIER_SELECTION_SOURCE,
    oc.CARRIER_SELECTION_RULE_ID,
    oc.CARRIER_SELECTED_DSTAMP,
    oc.CARRIER_OVERRIDE_REASON,
    CASE
        WHEN oc.CARRIER_ID IS NULL THEN 'NEEDS_SELECTION'
        WHEN oc.CARRIER_SELECTION_SOURCE='MANUAL_OVERRIDE' THEN 'OVERRIDDEN'
        ELSE 'SELECTED'
    END AS SELECTION_STATUS
FROM core.ORDER_CONTAINER oc
JOIN core.ORDER_HEADER oh
  ON oh.CLIENT_ID=oc.CLIENT_ID AND oh.ORDER_ID=oc.ORDER_ID
WHERE oc.STATUS <> 'SHIPPED';
