CREATE OR REPLACE VIEW core.CONTAINER_MERGE_CANDIDATE_WORKBENCH AS
SELECT
    a.CLIENT_ID,
    a.ORDER_ID,
    a.CONTAINER_ID AS LEFT_CONTAINER_ID,
    b.CONTAINER_ID AS RIGHT_CONTAINER_ID,
    a.DELIVERY_CLASS AS LEFT_DELIVERY_CLASS,
    b.DELIVERY_CLASS AS RIGHT_DELIVERY_CLASS,
    a.FULFILMENT_METHOD AS LEFT_FULFILMENT_METHOD,
    b.FULFILMENT_METHOD AS RIGHT_FULFILMENT_METHOD,
    a.HOLD_STATUS AS LEFT_HOLD_STATUS,
    b.HOLD_STATUS AS RIGHT_HOLD_STATUS,
    COALESCE(a.WEIGHT,0)+COALESCE(b.WEIGHT,0) AS COMBINED_WEIGHT,
    COALESCE(a.VOLUME,0)+COALESCE(b.VOLUME,0) AS COMBINED_VOLUME,
    oh.FULFILMENT_PREFERENCE,
    e.RESULT_ALLOWED AS MERGE_ALLOWED,
    e.RESULT_RULE_ID AS MERGE_RULE_ID,
    e.RESULT_RULE_NAME AS MERGE_RULE_NAME,
    e.RESULT_REASON AS MERGE_REASON
FROM core.ORDER_CONTAINER a
JOIN core.ORDER_CONTAINER b
  ON b.CLIENT_ID=a.CLIENT_ID
 AND b.ORDER_ID=a.ORDER_ID
 AND b.CONTAINER_ID>a.CONTAINER_ID
JOIN core.ORDER_HEADER oh
  ON oh.CLIENT_ID=a.CLIENT_ID
 AND oh.ORDER_ID=a.ORDER_ID
CROSS JOIN LATERAL core.EVALUATE_CONTAINER_MERGE(
    a.CLIENT_ID,a.CONTAINER_ID,b.CONTAINER_ID
) e
WHERE UPPER(COALESCE(a.STATUS,'')) NOT IN ('SHIPPED','MERGED','CANCELLED')
  AND UPPER(COALESCE(b.STATUS,'')) NOT IN ('SHIPPED','MERGED','CANCELLED');
