CREATE OR REPLACE VIEW core.DELIVERY_HOLD_WORKBENCH AS
SELECT
    oc.CLIENT_ID,
    oc.ORDER_ID,
    oc.CONTAINER_ID,
    oc.DELIVERY_CLASS,
    oc.FULFILMENT_METHOD,
    oc.STATUS AS CONTAINER_STATUS,
    oc.HOLD_STATUS,
    oc.HOLD_REASON,
    oc.HOLD_SOURCE,
    oc.HOLD_DSTAMP,
    oc.RELEASE_DSTAMP,
    oc.RELEASED_BY,
    oh.FULFILMENT_PREFERENCE,
    oh.CUSTOMER_ID,
    oh.POSTCODE,
    oh.COUNTRY
FROM core.ORDER_CONTAINER oc
JOIN core.ORDER_HEADER oh
  ON oh.CLIENT_ID=oc.CLIENT_ID AND oh.ORDER_ID=oc.ORDER_ID
WHERE oc.HOLD_STATUS<>'NONE'
   OR UPPER(COALESCE(oc.DELIVERY_CLASS,'STANDARD'))='LIVESTOCK';
