-- INVENTORY_AVAILABILITY
-- Read-only operational view of physical, reserved and available inventory.

CREATE OR REPLACE VIEW core.INVENTORY_AVAILABILITY AS
SELECT
    i.KEY AS INVENTORY_KEY,
    i.CLIENT_ID,
    i.SKU_ID,
    i.SITE_ID,
    i.LOCATION_ID,
    i.OWNER_ID,
    i.BATCH_ID,
    i.CONDITION_ID,
    i.LOCK_STATUS,
    i.DISALLOW_ALLOC,
    i.QTY_ON_HAND,
    i.QTY_ALLOCATED,
    (i.QTY_ON_HAND - i.QTY_ALLOCATED) AS QTY_AVAILABLE,
    i.RECEIPT_DSTAMP,
    i.EXPIRY_DSTAMP,
    l.ACTIVE AS LOCATION_ACTIVE,
    l.LOCK_STATUS AS LOCATION_LOCK_STATUS,
    l.DISALLOW_ALLOC AS LOCATION_DISALLOW_ALLOC,
    CASE
        WHEN UPPER(COALESCE(i.DISALLOW_ALLOC, 'N')) = 'Y' THEN 'N'
        WHEN UPPER(COALESCE(i.LOCK_STATUS, '')) IN ('LOCKED', 'HOLD', 'QUARANTINE') THEN 'N'
        WHEN UPPER(COALESCE(l.DISALLOW_ALLOC, 'N')) = 'Y' THEN 'N'
        WHEN UPPER(COALESCE(l.LOCK_STATUS, '')) IN ('LOCKED', 'HOLD', 'QUARANTINE') THEN 'N'
        WHEN UPPER(COALESCE(l.ACTIVE, 'Y')) <> 'Y' THEN 'N'
        WHEN (i.QTY_ON_HAND - i.QTY_ALLOCATED) <= 0 THEN 'N'
        ELSE 'Y'
    END AS ALLOCATABLE
FROM core.INVENTORY i
JOIN core.LOCATION l
  ON l.LOCATION_ID = i.LOCATION_ID;

COMMENT ON VIEW core.INVENTORY_AVAILABILITY IS
    'Operational availability view: QTY_ON_HAND minus QTY_ALLOCATED plus allocatable status.';
