CREATE OR REPLACE VIEW core.INVENTORY_RESERVATION_RECONCILIATION AS
SELECT
    i.KEY AS INVENTORY_KEY,i.CLIENT_ID,i.SKU_ID,i.LOCATION_ID,i.QTY_ON_HAND,i.QTY_ALLOCATED,
    COALESCE(SUM(GREATEST(0,a.QTY_ALLOCATED-a.QTY_PICKED-a.QTY_RELEASED)),0) AS EXPECTED_QTY_ALLOCATED,
    i.QTY_ALLOCATED-COALESCE(SUM(GREATEST(0,a.QTY_ALLOCATED-a.QTY_PICKED-a.QTY_RELEASED)),0) AS RESERVATION_DIFFERENCE,
    CASE WHEN i.QTY_ALLOCATED=COALESCE(SUM(GREATEST(0,a.QTY_ALLOCATED-a.QTY_PICKED-a.QTY_RELEASED)),0)
         THEN 'OK' ELSE 'MISMATCH' END AS RECONCILIATION_STATUS
FROM core.INVENTORY i
LEFT JOIN core.ALLOCATION a ON a.INVENTORY_KEY=i.KEY
GROUP BY i.KEY,i.CLIENT_ID,i.SKU_ID,i.LOCATION_ID,i.QTY_ON_HAND,i.QTY_ALLOCATED;
