CREATE OR REPLACE VIEW core.MERGE_DECISION_EXPLANATION AS
SELECT
    DECISION_ID,
    CLIENT_ID,
    ENTITY_ID AS SOURCE_CONTAINER_ID,
    RULE_ID,
    RULE_NAME,
    DECISION,
    REASON,
    DETAIL,
    CREATED_DSTAMP
FROM audit.RULE_DECISION_LOG
WHERE ENGINE_NAME='CONTAINER_MERGE';
