CREATE OR REPLACE VIEW core.MIXED_ORDER_FULFILMENT_WORKBENCH AS
WITH x AS (
    SELECT
        oh.CLIENT_ID,
        oh.ORDER_ID,
        oh.FULFILMENT_PREFERENCE,
        COUNT(*) AS CONTAINER_COUNT,
        COUNT(*) FILTER (WHERE UPPER(COALESCE(oc.DELIVERY_CLASS,'STANDARD'))='LIVESTOCK') AS LIVESTOCK_CONTAINERS,
        COUNT(*) FILTER (WHERE UPPER(COALESCE(oc.DELIVERY_CLASS,'STANDARD'))<>'LIVESTOCK') AS NON_LIVE_CONTAINERS,
        COUNT(*) FILTER (WHERE oc.HOLD_STATUS<>'NONE') AS HELD_CONTAINERS,
        COUNT(*) FILTER (
            WHERE UPPER(COALESCE(oc.DELIVERY_CLASS,'STANDARD'))<>'LIVESTOCK'
              AND oc.HOLD_STATUS='NONE'
              AND oc.STATUS IN ('PACKED','READY_TO_SHIP','OPEN')
        ) AS NON_LIVE_READY
    FROM core.ORDER_HEADER oh
    JOIN core.ORDER_CONTAINER oc
      ON oc.CLIENT_ID=oh.CLIENT_ID AND oc.ORDER_ID=oh.ORDER_ID
    GROUP BY oh.CLIENT_ID,oh.ORDER_ID,oh.FULFILMENT_PREFERENCE
)
SELECT *,
    CASE
        WHEN LIVESTOCK_CONTAINERS>0 AND NON_LIVE_CONTAINERS>0
             AND FULFILMENT_PREFERENCE='SPLIT_WHEN_REQUIRED'
             AND NON_LIVE_READY>0
            THEN 'RELEASE_NON_LIVE'
        WHEN LIVESTOCK_CONTAINERS>0 AND NON_LIVE_CONTAINERS>0
             AND FULFILMENT_PREFERENCE='CONSOLIDATE'
            THEN 'HOLD_FOR_COMBINED_DELIVERY'
        WHEN HELD_CONTAINERS>0
            THEN 'REVIEW_HOLD'
        ELSE 'NORMAL_FULFILMENT'
    END AS RECOMMENDED_ACTION
FROM x;
