CREATE OR REPLACE VIEW core.ORDER_FULFILMENT_WORKBENCH AS
SELECT
    oh.CLIENT_ID,oh.ORDER_ID,oh.CUSTOMER_ID,oh.PRIORITY,oh.ORDER_DATE,oh.SHIP_BY_DATE,
    oh.DISPATCH_METHOD,oh.CARRIER_ID,oh.SERVICE_LEVEL,oh.FULFILMENT_STATUS,
    COUNT(ol.LINE_ID) AS LINE_COUNT,
    SUM(ol.QTY_ORDERED) AS QTY_ORDERED,
    SUM(COALESCE(ol.QTY_SOFT_ALLOCATED,0)) AS QTY_RESERVED,
    SUM(COALESCE(ol.QTY_PICKED,0)) AS QTY_PICKED,
    SUM(COALESCE(ol.QTY_SHIPPED,0)) AS QTY_SHIPPED,
    CASE
        WHEN SUM(COALESCE(ol.QTY_SHIPPED,0)) >= SUM(ol.QTY_ORDERED) THEN 'SHIPPED'
        WHEN SUM(COALESCE(ol.QTY_PICKED,0)) >= SUM(ol.QTY_ORDERED) THEN 'READY_TO_PACK'
        WHEN SUM(COALESCE(ol.QTY_PICKED,0)) > 0 THEN 'PART_PICKED'
        WHEN SUM(COALESCE(ol.QTY_SOFT_ALLOCATED,0)) >= SUM(ol.QTY_ORDERED) THEN 'ALLOCATED'
        WHEN SUM(COALESCE(ol.QTY_SOFT_ALLOCATED,0)) > 0 THEN 'PART_ALLOCATED'
        ELSE 'UNALLOCATED'
    END AS DERIVED_STATUS
FROM core.ORDER_HEADER oh
JOIN core.ORDER_LINE ol ON ol.CLIENT_ID=oh.CLIENT_ID AND ol.ORDER_ID=oh.ORDER_ID
GROUP BY oh.CLIENT_ID,oh.ORDER_ID,oh.CUSTOMER_ID,oh.PRIORITY,oh.ORDER_DATE,oh.SHIP_BY_DATE,
         oh.DISPATCH_METHOD,oh.CARRIER_ID,oh.SERVICE_LEVEL,oh.FULFILMENT_STATUS;
