CREATE OR REPLACE VIEW core.PICK_WORK_QUEUE AS
SELECT
    pt.PICK_TASK_ID,pt.CLIENT_ID,pt.ORDER_ID,pt.LINE_ID,pt.SKU_ID,pt.LOCATION_ID,pt.BATCH_ID,
    pt.QTY_REQUIRED,pt.QTY_PICKED,pt.SHORT_QTY,
    GREATEST(0,pt.QTY_REQUIRED-pt.QTY_PICKED-pt.SHORT_QTY) AS QTY_REMAINING,
    pt.STATUS,pt.SHORT_REASON,pt.CREATED_DSTAMP,pt.STARTED_DSTAMP,pt.COMPLETED_DSTAMP,
    oh.PRIORITY,oh.SHIP_BY_DATE,oh.DELIVER_BY_DATE
FROM core.PICK_TASK pt
JOIN core.ORDER_HEADER oh ON oh.CLIENT_ID=pt.CLIENT_ID AND oh.ORDER_ID=pt.ORDER_ID;
