CREATE OR REPLACE VIEW core.SHIPMENT_WORK_QUEUE AS
SELECT
    oc.CLIENT_ID,oc.ORDER_ID,oc.CONTAINER_ID,oc.STATUS AS CONTAINER_STATUS,
    COUNT(sm.KEY) AS MANIFEST_ROWS,
    COALESCE(SUM(sm.QTY_PICKED),0) AS QTY_PACKED,
    COALESCE(SUM(sm.QTY_SHIPPED),0) AS QTY_SHIPPED,
    oc.CARRIER_ID,oc.SERVICE_LEVEL,oc.TRACKING_NUMBER,oc.CREATED_DSTAMP,oc.CLOSED_DSTAMP
FROM core.ORDER_CONTAINER oc
LEFT JOIN core.SHIPPING_MANIFEST sm ON sm.CLIENT_ID=oc.CLIENT_ID AND sm.CONTAINER_ID=oc.CONTAINER_ID
GROUP BY oc.CLIENT_ID,oc.ORDER_ID,oc.CONTAINER_ID,oc.STATUS,oc.CARRIER_ID,oc.SERVICE_LEVEL,
         oc.TRACKING_NUMBER,oc.CREATED_DSTAMP,oc.CLOSED_DSTAMP;
