import React,{useCallback,useEffect,useMemo,useState} from "react";
import ReactDOM from "react-dom/client";
import {Auth0Provider,useAuth0} from "@auth0/auth0-react";
import "./styles.css";

type Obj=Record<string,unknown>;
type Me={adminUserId:string;email:string;displayName:string|null;roles:string[];permissions:string[];bootstrap:boolean};
const BASE=(import.meta.env.VITE_API_BASE_URL||"https://api.finaticsaquatics.co.uk").replace(/\/$/,"");
const get=(r:Obj,...k:string[])=>{for(const x of k)if(r[x]!==undefined)return r[x]};
const txt=(v:unknown,f="â€”")=>v===null||v===undefined||v===""?f:String(v);
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const money=(v:unknown,c="GBP")=>Number.isFinite(Number(v))?new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(Number(v)):"â€”";
const dt=(v:unknown)=>{if(!v)return"â€”";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-GB")};
class ApiError extends Error{status:number;constructor(s:number,m:string){super(m);this.status=s}}
async function req<T>(token:()=>Promise<string>,path:string,init:RequestInit={}):Promise<T>{
  const h=new Headers(init.headers);h.set("Accept","application/json");h.set("Authorization",`Bearer ${await token()}`);if(init.body)h.set("Content-Type","application/json");
  const r=await fetch(BASE+path,{...init,headers:h});const raw=await r.text();let b:any=null;try{b=raw?JSON.parse(raw):null}catch{b=raw}
  if(!r.ok)throw new ApiError(r.status,String(b?.error||b?.message||`HTTP_${r.status}`));return b as T;
}
const Q=(x:Obj)=>{const s=new URLSearchParams();Object.entries(x).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")s.set(k,String(v))});return s.size?`?${s}`:""};

function Button({children,onClick,disabled,kind=""}:{children:React.ReactNode;onClick?:()=>void;disabled?:boolean;kind?:string}){return <button className={`btn ${kind}`} onClick={onClick} disabled={disabled}>{children}</button>}
function Pill({children,tone=""}:{children:React.ReactNode;tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}
function Card({children,wide=false}:{children:React.ReactNode;wide?:boolean}){return <section className={`card ${wide?"wide":""}`}>{children}</section>}
function Header({title,sub,action}:{title:string;sub?:string;action?:React.ReactNode}){return <div className="head"><div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{action}</div>}
function Load(){return <div className="load"><i/>Loadingâ€¦</div>}
function ErrorBox({e}:{e:unknown}){return <div className="error"><strong>Could not load this area</strong><span>{e instanceof Error?e.message:String(e)}</span></div>}
function Search({value,setValue,placeholder}:{value:string;setValue:(v:string)=>void;placeholder:string}){return <input className="input search" value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="shade" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modalhead"><h2>{title}</h2><Button kind="ghost" onClick={onClose}>Close</Button></div><div className="modalbody">{children}</div></div></div>}
function Table({rows,cols,keyOf,onClick}:{rows:Obj[];cols:{name:string;cell:(r:Obj)=>React.ReactNode}[];keyOf:(r:Obj,i:number)=>string;onClick?:(r:Obj)=>void}){return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th key={c.name}>{c.name}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={keyOf(r,i)} className={onClick?"click":""} onClick={()=>onClick?.(r)}>{cols.map(c=><td key={c.name}>{c.cell(r)}</td>)}</tr>)}</tbody></table></div>}

function Dashboard({token,me}:{token:()=>Promise<string>;me:Me}){
  const[d,setD]=useState<Obj|null>(null),[e,setE]=useState<unknown>(null);
  useEffect(()=>{req<Obj>(token,"/api/admin/dashboard").then(setD).catch(setE)},[token]);
  if(e)return <ErrorBox e={e}/>;if(!d)return <Load/>;
  const metrics=[["Products",get(d,"product_count","productCount","products")],["Active products",get(d,"active_product_count","activeProductCount","activeProducts")],["SKUs",get(d,"sku_count","skuCount","skus")],["On hand",get(d,"qty_on_hand","qtyOnHand","inventoryQty")],["Available",get(d,"available_qty","availableQty")],["Orders",get(d,"order_count","orderCount","orders")],["Open orders",get(d,"open_order_count","openOrderCount","openOrders")],["Pending payment",get(d,"pending_payment_count","pendingPaymentCount","pendingPayments")]].filter(x=>x[1]!==undefined);
  return <><Header title="Control centre" sub={`Signed in as ${me.displayName||me.email}. DYNETIC remains authoritative for stock, orders, pricing and permissions.`}/><div className="metrics">{metrics.map(([k,v])=><Card key={String(k)}><span>{String(k)}</span><strong>{num(v)}</strong></Card>)}</div><div className="grid2"><Card><h2>Access</h2><Pill tone="good">{me.roles.join(", ")}</Pill><p className="muted">{me.permissions.length} permissions resolved from DYNETIC RBAC.</p><div className="cloud">{me.permissions.map(p=><code key={p}>{p}</code>)}</div></Card><Card><h2>System snapshot</h2><dl>{Object.entries(d).slice(0,16).map(([k,v])=><div key={k}><dt>{k.replace(/_/g," ")}</dt><dd>{typeof v==="object"?"Available in detail":txt(v)}</dd></div>)}</dl></Card></div></>;
}

function Products({token}:{token:()=>Promise<string>}){
  const[q,setQ]=useState(""),[rows,setRows]=useState<Obj[]>([]),[sel,setSel]=useState<Obj|null>(null),[detail,setDetail]=useState<Obj|null>(null),[e,setE]=useState<unknown>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);req<any>(token,"/api/admin/products"+Q({q:q||undefined,limit:200})).then(x=>live&&setRows(Array.isArray(x)?x:x?.items||[])).catch(setE).finally(()=>live&&setLoading(false));return()=>{live=false}},[token,q]);
  useEffect(()=>{if(!sel){setDetail(null);return}const id=txt(get(sel,"product_id","productId"),"");if(id)req<Obj>(token,`/api/admin/products/${encodeURIComponent(id)}`).then(setDetail).catch(setE)},[sel,token]);
  const cols=[{name:"Product",cell:(r:Obj)=><><strong>{txt(get(r,"product_name","productName","name"))}</strong><small>{txt(get(r,"product_id","productId"))}</small></>},{name:"Category",cell:(r:Obj)=>txt(get(r,"category_name","categoryName","category_id","categoryId"))},{name:"Variants",cell:(r:Obj)=>num(get(r,"variant_count","variantCount"))},{name:"From",cell:(r:Obj)=>money(get(r,"from_price","fromPrice","web_price","webPrice"),String(get(r,"currency")||"GBP"))},{name:"Available",cell:(r:Obj)=>num(get(r,"available_qty","availableQty"))},{name:"Status",cell:(r:Obj)=>get(r,"active")===false?<Pill tone="bad">Inactive</Pill>:<Pill tone="good">Active</Pill>}];
  return <><Header title="Products" sub="Catalogue, variants, sale state and pricing from DYNETIC."/><Card><div className="toolbar"><Search value={q} setValue={setQ} placeholder="Search products, SKU or categoryâ€¦"/><span>{rows.length} products</span></div>{e?<ErrorBox e={e}/>:loading?<Load/>:<Table rows={rows} cols={cols} keyOf={(r,i)=>txt(get(r,"product_id","productId"),String(i))} onClick={setSel}/>}</Card>{sel&&<Modal title={txt(get(sel,"product_name","productName"),"Product")} onClose={()=>setSel(null)}>{!detail?<Load/>:<><div className="notice">Read/detail experience is live. Product and pricing mutation buttons are held back until the API request fields are explicitly contract-tested; this UI never writes directly to tables.</div><dl>{Object.entries(detail).filter(([k])=>k!=="variants").slice(0,24).map(([k,v])=><div key={k}><dt>{k.replace(/_/g," ")}</dt><dd>{typeof v==="object"?JSON.stringify(v):txt(v)}</dd></div>)}</dl>{Array.isArray(detail.variants)&&<><h3>Variants</h3><div className="variants">{(detail.variants as Obj[]).map((v,i)=><div key={txt(get(v,"sku_id","skuId"),String(i))}><strong>{txt(get(v,"variant_name","variantName","sku_id","skuId"))}</strong><span>{txt(get(v,"sku_id","skuId"))}</span><span>{money(get(v,"web_price","webPrice"))}</span><span>Available {num(get(v,"available_qty","availableQty"))}</span></div>)}</div></>}</>}</Modal>}</>;
}

function Inventory({token,canAdjust}:{token:()=>Promise<string>;canAdjust:boolean}){
  const[q,setQ]=useState(""),[rows,setRows]=useState<Obj[]>([]),[e,setE]=useState<unknown>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);req<any>(token,"/api/admin/inventory"+Q({q:q||undefined,limit:250})).then(x=>live&&setRows(Array.isArray(x)?x:x?.items||[])).catch(setE).finally(()=>live&&setLoading(false));return()=>{live=false}},[token,q]);
  const cols=[{name:"SKU",cell:(r:Obj)=><><strong>{txt(get(r,"sku_id","skuId"))}</strong><small>{txt(get(r,"product_name","productName","variant_name","variantName"))}</small></>},{name:"Location",cell:(r:Obj)=>txt(get(r,"location_id","locationId","location"))},{name:"On hand",cell:(r:Obj)=>num(get(r,"qty_on_hand","qtyOnHand"))},{name:"Allocated",cell:(r:Obj)=>num(get(r,"qty_allocated","qtyAllocated"))},{name:"Available",cell:(r:Obj)=>num(get(r,"available_qty","availableQty","qty_available"))}];
  return <><Header title="Inventory" sub="Live stock browser. No direct quantity edits are permitted." />{canAdjust&&<div className="notice">Your OWNER role includes inventory.adjust. Adjustment UI will activate only after a dedicated authoritative adjustment endpoint exists.</div>}<Card><div className="toolbar"><Search value={q} setValue={setQ} placeholder="Search SKU, product or locationâ€¦"/><span>{rows.length} rows</span></div>{e?<ErrorBox e={e}/>:loading?<Load/>:<Table rows={rows} cols={cols} keyOf={(r,i)=>`${txt(get(r,"sku_id","skuId"),String(i))}-${txt(get(r,"location_id","locationId"),String(i))}`}/>}</Card></>;
}

function Orders({token}:{token:()=>Promise<string>}){
  const[q,setQ]=useState(""),[rows,setRows]=useState<Obj[]>([]),[sel,setSel]=useState<Obj|null>(null),[detail,setDetail]=useState<Obj|null>(null),[e,setE]=useState<unknown>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);req<any>(token,"/api/admin/orders"+Q({q:q||undefined,limit:250})).then(x=>live&&setRows(Array.isArray(x)?x:x?.items||[])).catch(setE).finally(()=>live&&setLoading(false));return()=>{live=false}},[token,q]);
  useEffect(()=>{if(!sel){setDetail(null);return}const id=txt(get(sel,"order_id","orderId"),"");if(id)req<Obj>(token,`/api/admin/orders/${encodeURIComponent(id)}`).then(setDetail).catch(setE)},[sel,token]);
  const cols=[{name:"Order",cell:(r:Obj)=><><strong>{txt(get(r,"order_id","orderId","order_reference","orderReference"))}</strong><small>{dt(get(r,"order_date","orderDate","created_dstamp","createdAt"))}</small></>},{name:"Customer",cell:(r:Obj)=>txt(get(r,"customer_email","customerEmail","email"))},{name:"Status",cell:(r:Obj)=><Pill>{txt(get(r,"status"))}</Pill>},{name:"Payment",cell:(r:Obj)=><Pill tone={txt(get(r,"payment_status","paymentStatus"))==="PAID"?"good":"warn"}>{txt(get(r,"payment_status","paymentStatus"))}</Pill>},{name:"Fulfilment",cell:(r:Obj)=>txt(get(r,"fulfilment_status","fulfilmentStatus"))},{name:"Value",cell:(r:Obj)=>money(get(r,"order_value","orderValue","total"),String(get(r,"inv_currency","currency")||"GBP"))}];
  return <><Header title="Orders" sub="Operational order and payment visibility from DYNETIC."/><Card><div className="toolbar"><Search value={q} setValue={setQ} placeholder="Search order, customer or statusâ€¦"/><span>{rows.length} orders</span></div>{e?<ErrorBox e={e}/>:loading?<Load/>:<Table rows={rows} cols={cols} keyOf={(r,i)=>txt(get(r,"order_id","orderId"),String(i))} onClick={setSel}/>}</Card>{sel&&<Modal title={`Order ${txt(get(sel,"order_id","orderId"))}`} onClose={()=>setSel(null)}>{!detail?<Load/>:<><div className="notice">Order update/cancel permissions exist, but mutation controls stay disabled until dedicated endpoints are implemented. The portal will not manipulate fulfilment tables directly.</div><dl>{Object.entries(detail).filter(([,v])=>!Array.isArray(v)&&typeof v!=="object").map(([k,v])=><div key={k}><dt>{k.replace(/_/g," ")}</dt><dd>{txt(v)}</dd></div>)}</dl>{Array.isArray(detail.lines)&&<pre>{JSON.stringify(detail.lines,null,2)}</pre>}</>}</Modal>}</>;
}

function Access({token,has}:{token:()=>Promise<string>;has:(p:string)=>boolean}){
  const[users,setUsers]=useState<Obj[]>([]),[roles,setRoles]=useState<Obj[]>([]),[permissions,setPermissions]=useState<Obj[]>([]),[e,setE]=useState<unknown>(null),[loading,setLoading]=useState(true),[add,setAdd]=useState(false),[edit,setEdit]=useState<Obj|null>(null),[nonce,setNonce]=useState(0);
  useEffect(()=>{let live=true;setLoading(true);Promise.all([req<Obj[]>(token,"/api/admin/users"),req<Obj[]>(token,"/api/admin/roles"),req<Obj[]>(token,"/api/admin/permissions")]).then(([u,r,p])=>{if(live){setUsers(u);setRoles(r);setPermissions(p)}}).catch(setE).finally(()=>live&&setLoading(false));return()=>{live=false}},[token,nonce]);
  if(e)return <ErrorBox e={e}/>;if(loading)return <Load/>;
  return <><Header title="Users & access" sub="Auth0 proves identity; DYNETIC decides internal access." action={has("user.create")?<Button onClick={()=>setAdd(true)}>Add staff user</Button>:undefined}/><div className="grid2"><Card><h2>Staff users</h2><div className="users">{users.map((u,i)=><button key={txt(get(u,"admin_user_id","adminUserId"),String(i))} onClick={()=>setEdit(u)}><div><strong>{txt(get(u,"display_name","displayName","email"))}</strong><span>{txt(get(u,"email"))}</span></div><div>{(get(u,"roles") as string[]||[]).map(r=><Pill key={r} tone={r==="OWNER"?"good":""}>{r}</Pill>)}</div></button>)}</div></Card><Card><h2>Roles</h2><div className="roles">{roles.map((r,i)=><div key={txt(get(r,"role_code","roleCode"),String(i))}><strong>{txt(get(r,"role_name","roleName"))}</strong><Pill>{txt(get(r,"role_code","roleCode"))}</Pill><p>{txt(get(r,"description"),"No description")}</p><small>{(get(r,"permissions") as unknown[]||[]).length} permissions</small></div>)}</div></Card><Card wide><h2>Permission catalogue</h2><div className="perms">{permissions.map((p,i)=><div key={txt(get(p,"permission_code","permissionCode"),String(i))}><code>{txt(get(p,"permission_code","permissionCode"))}</code><span>{txt(get(p,"description"))}</span>{get(p,"dangerous")===true&&<Pill tone="warn">Sensitive</Pill>}</div>)}</div></Card></div>{add&&<UserModal token={token} roles={roles} onClose={()=>setAdd(false)} onDone={()=>{setAdd(false);setNonce(x=>x+1)}}/>}{edit&&<UserModal token={token} roles={roles} user={edit} onClose={()=>setEdit(null)} onDone={()=>{setEdit(null);setNonce(x=>x+1)}}/>}</>;
}
function UserModal({token,roles,user,onClose,onDone}:{token:()=>Promise<string>;roles:Obj[];user?:Obj;onClose:()=>void;onDone:()=>void}){
  const[email,setEmail]=useState(txt(user&&get(user,"email"),"")),[name,setName]=useState(txt(user&&get(user,"display_name","displayName"),"")),[selected,setSelected]=useState<string[]>((user&&get(user,"roles") as string[])||["VIEWER"]),[saving,setSaving]=useState(false),[err,setErr]=useState("");
  const codes=roles.filter(r=>get(r,"active")!==false).map(r=>txt(get(r,"role_code","roleCode")));
  async function save(){setSaving(true);setErr("");try{if(!user){await req(token,"/api/admin/users",{method:"POST",body:JSON.stringify({email,displayName:name,roles:selected})})}else{const id=txt(get(user,"admin_user_id","adminUserId"));await req(token,`/api/admin/users/${id}`,{method:"PATCH",body:JSON.stringify({displayName:name})});await req(token,`/api/admin/users/${id}/roles`,{method:"PUT",body:JSON.stringify({roles:selected})})}onDone()}catch(e){setErr(e instanceof Error?e.message:String(e))}finally{setSaving(false)}}
  return <Modal title={user?"Edit staff user":"Add staff user"} onClose={onClose}><div className="form"><label>Email<input className="input" disabled={!!user} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Display name<input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><fieldset><legend>DYNETIC roles</legend>{codes.map(c=><label key={c} className="check"><input type="checkbox" checked={selected.includes(c)} onChange={e=>setSelected(x=>e.target.checked?[...x,c]:x.filter(v=>v!==c))}/>{c}</label>)}</fieldset>{err&&<div className="formerr">{err}</div>}<div className="actions"><Button kind="ghost" onClick={onClose}>Cancel</Button><Button onClick={save} disabled={saving||!email}>{saving?"Savingâ€¦":"Save"}</Button></div></div></Modal>;
}

function Audit({token}:{token:()=>Promise<string>}){
  const[rows,setRows]=useState<Obj[]>([]),[filter,setFilter]=useState(""),[e,setE]=useState<unknown>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);req<Obj[]>(token,"/api/admin/audit"+Q({entityType:filter||undefined,limit:200})).then(x=>live&&setRows(x)).catch(setE).finally(()=>live&&setLoading(false));return()=>{live=false}},[token,filter]);
  const cols=[{name:"When",cell:(r:Obj)=>dt(get(r,"created_dstamp","createdDstamp"))},{name:"Entity",cell:(r:Obj)=><><strong>{txt(get(r,"entity_type","entityType"))}</strong><small>{txt(get(r,"entity_id","entityId"))}</small></>},{name:"Action",cell:(r:Obj)=><Pill>{txt(get(r,"action"))}</Pill>},{name:"Changed by",cell:(r:Obj)=>txt(get(r,"changed_by","changedBy"))},{name:"Reason",cell:(r:Obj)=>txt(get(r,"reason"))}];
  return <><Header title="Audit trail" sub="Administrative changes recorded by DYNETIC."/><Card><div className="toolbar"><Search value={filter} setValue={setFilter} placeholder="Filter entity typeâ€¦"/><span>Latest {rows.length}</span></div>{e?<ErrorBox e={e}/>:loading?<Load/>:<Table rows={rows} cols={cols} keyOf={(r,i)=>txt(get(r,"audit_id","auditId"),String(i))}/>}</Card></>;
}

type Page="dashboard"|"products"|"inventory"|"orders"|"access"|"audit";
function App(){
  const{isLoading,isAuthenticated,loginWithRedirect,logout,getAccessTokenSilently}=useAuth0();
  const[me,setMe]=useState<Me|null>(null),[e,setE]=useState<unknown>(null),[page,setPage]=useState<Page>("dashboard");
  const token=useCallback(async()=>{const t=await getAccessTokenSilently({authorizationParams:{audience:import.meta.env.VITE_AUTH0_AUDIENCE||"https://api.finaticsaquatics.co.uk"}});if(!t)throw new Error("AUTH_TOKEN_MISSING");return t},[getAccessTokenSilently]);
  useEffect(()=>{if(isAuthenticated)req<Me>(token,"/api/admin/me").then(setMe).catch(setE)},[isAuthenticated,token]);
  const has=useCallback((p:string)=>!!me?.permissions.includes(p),[me]);
  const nav=useMemo(()=>[{p:"dashboard" as Page,l:"Dashboard",perm:"dashboard.read"},{p:"products" as Page,l:"Products",perm:"product.read"},{p:"inventory" as Page,l:"Inventory",perm:"inventory.read"},{p:"orders" as Page,l:"Orders",perm:"order.read"},{p:"access" as Page,l:"Users & roles",perm:"user.read"},{p:"audit" as Page,l:"Audit",perm:"audit.read"}].filter(x=>has(x.perm)),[has]);
  if(isLoading)return <div className="splash"><Load/></div>;
  if(!isAuthenticated)return <div className="splash"><div className="login"><div className="logo">FA</div><h1>FINatics Control</h1><p>Internal operations portal powered by DYNETIC WMS.</p><Button onClick={()=>loginWithRedirect()}>Sign in with Auth0</Button></div></div>;
  if(e)return <div className="splash"><div className="login"><h1>Admin access unavailable</h1><ErrorBox e={e}/><Button kind="ghost" onClick={()=>logout({logoutParams:{returnTo:location.origin}})}>Sign out</Button></div></div>;
  if(!me)return <div className="splash"><Load/></div>;
  return <div className="shell"><aside><div className="brand"><div className="logo small">FA</div><div><strong>{import.meta.env.VITE_ADMIN_TITLE||"FINatics Control"}</strong><span>DYNETIC WMS</span></div></div><nav>{nav.map(n=><button className={page===n.p?"active":""} key={n.p} onClick={()=>setPage(n.p)}>{n.l}</button>)}</nav><div className="foot"><strong>{me.displayName||me.email}</strong><span>{me.roles.join(", ")}</span><button onClick={()=>logout({logoutParams:{returnTo:location.origin}})}>Sign out</button></div></aside><main>{page==="products"?<Products token={token}/>:page==="inventory"?<Inventory token={token} canAdjust={has("inventory.adjust")}/>:page==="orders"?<Orders token={token}/>:page==="access"?<Access token={token} has={has}/>:page==="audit"?<Audit token={token}/>:<Dashboard token={token} me={me}/>}</main></div>;
}

const domain=import.meta.env.VITE_AUTH0_DOMAIN,clientId=import.meta.env.VITE_AUTH0_CLIENT_ID,audience=import.meta.env.VITE_AUTH0_AUDIENCE||"https://api.finaticsaquatics.co.uk";
if(!domain||!clientId)document.getElementById("root")!.innerHTML='<div style="font-family:system-ui;padding:40px"><h1>Admin configuration required</h1><p>Set VITE_AUTH0_DOMAIN and VITE_AUTH0_CLIENT_ID.</p></div>';
else ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><Auth0Provider domain={domain} clientId={clientId} cacheLocation="localstorage" useRefreshTokens authorizationParams={{redirect_uri:location.origin,audience,scope:"openid profile email"}}><App/></Auth0Provider></React.StrictMode>);
