-- Example only. Review before loading into a live FINatics client.

-- Allow mixed LIVESTOCK + STANDARD containers to consolidate when the entire
-- order is being handled by LOCAL_DELIVERY and the customer selected
-- CONSOLIDATE.
INSERT INTO config.MERGE_RULE (
    CLIENT_ID,RULE_NAME,PRIORITY,ACTIVE,DECISION,STOP_ON_MATCH
)
VALUES (
    'FINATICS',
    'ALLOW MIXED LOCAL DELIVERY',
    10,
    TRUE,
    'ALLOW',
    TRUE
)
ON CONFLICT (CLIENT_ID,RULE_NAME) DO NOTHING;

INSERT INTO config.MERGE_RULE_CONDITION (
    RULE_ID,FIELD_NAME,OPERATOR,VALUE_TEXT,CONDITION_GROUP,SEQUENCE
)
SELECT RULE_ID,'FULFILMENT_METHOD','EQ','LOCAL_DELIVERY',1,10
FROM config.MERGE_RULE
WHERE CLIENT_ID='FINATICS'
  AND RULE_NAME='ALLOW MIXED LOCAL DELIVERY'
  AND NOT EXISTS (
      SELECT 1
      FROM config.MERGE_RULE_CONDITION c
      WHERE c.RULE_ID=config.MERGE_RULE.RULE_ID
        AND c.FIELD_NAME='FULFILMENT_METHOD'
  );

INSERT INTO config.MERGE_RULE_CONDITION (
    RULE_ID,FIELD_NAME,OPERATOR,VALUE_TEXT,CONDITION_GROUP,SEQUENCE
)
SELECT RULE_ID,'FULFILMENT_PREFERENCE','EQ','CONSOLIDATE',1,20
FROM config.MERGE_RULE
WHERE CLIENT_ID='FINATICS'
  AND RULE_NAME='ALLOW MIXED LOCAL DELIVERY'
  AND NOT EXISTS (
      SELECT 1
      FROM config.MERGE_RULE_CONDITION c
      WHERE c.RULE_ID=config.MERGE_RULE.RULE_ID
        AND c.FIELD_NAME='FULFILMENT_PREFERENCE'
  );
