-- ALLOCATION
-- Exact order-demand to inventory-reservation relationship.

CREATE TABLE IF NOT EXISTS core.ALLOCATION (
    ALLOCATION_ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CLIENT_ID                      VARCHAR(10) NOT NULL,
    ORDER_ID                       VARCHAR(20) NOT NULL,
    LINE_ID                        NUMERIC(6) NOT NULL,
    INVENTORY_KEY                  BIGINT NOT NULL,
    QTY_ALLOCATED                  NUMERIC(15,6) NOT NULL,
    ALLOCATION_DSTAMP              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CREATED_BY                     VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    PRIMARY KEY (ALLOCATION_ID),
    FOREIGN KEY (CLIENT_ID, ORDER_ID, LINE_ID)
        REFERENCES core.ORDER_LINE (CLIENT_ID, ORDER_ID, LINE_ID),
    FOREIGN KEY (INVENTORY_KEY)
        REFERENCES core.INVENTORY (KEY),
    CONSTRAINT CK_ALLOCATION_QTY_POSITIVE CHECK (QTY_ALLOCATED > 0)
);

COMMENT ON TABLE core.ALLOCATION IS
    'Links order-line demand to the exact inventory records reserved to fulfil it.';
COMMENT ON COLUMN core.ALLOCATION.ALLOCATION_ID IS
    'Unique allocation/reservation identifier.';
COMMENT ON COLUMN core.ALLOCATION.CLIENT_ID IS
    'Client/business identifier.';
COMMENT ON COLUMN core.ALLOCATION.ORDER_ID IS
    'Order identifier.';
COMMENT ON COLUMN core.ALLOCATION.LINE_ID IS
    'Order line identifier.';
COMMENT ON COLUMN core.ALLOCATION.INVENTORY_KEY IS
    'Inventory record supplying the reservation.';
COMMENT ON COLUMN core.ALLOCATION.QTY_ALLOCATED IS
    'Quantity reserved from the inventory record for the order line.';
COMMENT ON COLUMN core.ALLOCATION.ALLOCATION_DSTAMP IS
    'Timestamp when the reservation was created.';
COMMENT ON COLUMN core.ALLOCATION.CREATED_BY IS
    'Process or user that created the reservation.';
