-- INVENTORY
-- Generic WMS core inventory.
-- KEY is generated by PostgreSQL for normal application use, while BY DEFAULT
-- still permits explicit keys during controlled migration/import.

CREATE TABLE IF NOT EXISTS core.INVENTORY (
    KEY                            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    TAG_ID                         VARCHAR(50),
    CONTAINER_ID                   VARCHAR(50),
    CLIENT_ID                      VARCHAR(10) NOT NULL,
    SKU_ID                         VARCHAR(50) NOT NULL,
    SITE_ID                        VARCHAR(10),
    LOCATION_ID                    VARCHAR(20) NOT NULL,
    OWNER_ID                       VARCHAR(10),
    QTY_ON_HAND                    NUMERIC(15,6) NOT NULL,
    QTY_ALLOCATED                  NUMERIC(15,6) NOT NULL,
    ORIGIN_ID                      VARCHAR(10),
    CONDITION_ID                   VARCHAR(10),
    LOCK_STATUS                    VARCHAR(20) NOT NULL,
    LOCK_CODE                      VARCHAR(10),
    RECEIPT_DSTAMP                 TIMESTAMPTZ NOT NULL,
    MOVE_DSTAMP                    TIMESTAMPTZ NOT NULL,
    RECEIPT_TYPE                   VARCHAR(1),
    RECEIPT_ID                     VARCHAR(20),
    LINE_ID                        NUMERIC(6),
    QC_STATUS                      VARCHAR(20),
    BATCH_ID                       VARCHAR(50),
    EXPIRY_DSTAMP                  TIMESTAMPTZ,
    MANUF_DSTAMP                   TIMESTAMPTZ,
    COUNT_DSTAMP                   TIMESTAMPTZ,
    COUNT_NEEDED                   VARCHAR(1),
    SUPPLIER_ID                    VARCHAR(15),
    DESCRIPTION                    VARCHAR(80),
    NOTES                          VARCHAR(80),
    DISALLOW_ALLOC                 VARCHAR(1),
    UNIT_COST                      NUMERIC(12,2),
    PRIMARY KEY (KEY),
    FOREIGN KEY (CLIENT_ID) REFERENCES core.CLIENT (CLIENT_ID),
    FOREIGN KEY (CLIENT_ID, SKU_ID) REFERENCES core.SKU (CLIENT_ID, SKU_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES core.LOCATION (LOCATION_ID)
);
