CREATE TABLE IF NOT EXISTS core.KIT_HEADER (
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    KIT_ID varchar(50) NOT NULL,
    KIT_SKU_ID varchar(50) NOT NULL,
    KIT_TYPE varchar(30) NOT NULL DEFAULT 'MANUFACTURE',
    DESCRIPTION varchar(150),
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, KIT_ID),
    FOREIGN KEY (CLIENT_ID, KIT_SKU_ID) REFERENCES core.SKU(CLIENT_ID, SKU_ID)
);
