CREATE TABLE IF NOT EXISTS core.KIT_LINE (
    CLIENT_ID varchar(30) NOT NULL,
    KIT_ID varchar(50) NOT NULL,
    LINE_ID integer NOT NULL,
    COMPONENT_SKU_ID varchar(50) NOT NULL,
    QTY numeric(18,6) NOT NULL,
    SEQUENCE integer NOT NULL DEFAULT 100,
    OPTIONAL_COMPONENT boolean NOT NULL DEFAULT false,
    SHOW_AS_REPLACEMENT boolean NOT NULL DEFAULT false,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, KIT_ID, LINE_ID),
    FOREIGN KEY (CLIENT_ID, KIT_ID) REFERENCES core.KIT_HEADER(CLIENT_ID, KIT_ID),
    FOREIGN KEY (CLIENT_ID, COMPONENT_SKU_ID) REFERENCES core.SKU(CLIENT_ID, SKU_ID)
);
