CREATE TABLE IF NOT EXISTS core.LOCATION_ZONE (
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    SITE_ID varchar(30) NOT NULL REFERENCES core.SITE(SITE_ID),
    ZONE_ID varchar(50) NOT NULL,
    DESCRIPTION varchar(120) NOT NULL,
    ZONE_TYPE varchar(30),
    PICK_SEQUENCE integer,
    PUTAWAY_SEQUENCE integer,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, SITE_ID, ZONE_ID)
);
