CREATE TABLE IF NOT EXISTS core.PRE_ADVICE_HEADER (
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    PRE_ADVICE_ID varchar(50) NOT NULL,
    SITE_ID varchar(30) NOT NULL REFERENCES core.SITE(SITE_ID),
    SUPPLIER_ID varchar(50),
    STATUS varchar(30) NOT NULL DEFAULT 'EXPECTED',
    SUPPLIER_REFERENCE varchar(100),
    CARRIER_REFERENCE varchar(100),
    DUE_DSTAMP timestamptz,
    ACTUAL_DSTAMP timestamptz,
    NOTES text,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, PRE_ADVICE_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES core.SUPPLIER(SUPPLIER_ID)
);
