CREATE TABLE IF NOT EXISTS core.PRE_ADVICE_LINE (
    CLIENT_ID varchar(30) NOT NULL,
    PRE_ADVICE_ID varchar(50) NOT NULL,
    LINE_ID integer NOT NULL,
    SKU_ID varchar(50) NOT NULL,
    QTY_DUE numeric(18,6) NOT NULL,
    QTY_RECEIVED numeric(18,6) NOT NULL DEFAULT 0,
    BATCH_ID varchar(80),
    EXPIRY_DSTAMP timestamptz,
    MANUF_DSTAMP timestamptz,
    CONDITION_ID varchar(30),
    NOTES text,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, PRE_ADVICE_ID, LINE_ID),
    FOREIGN KEY (CLIENT_ID, PRE_ADVICE_ID) REFERENCES core.PRE_ADVICE_HEADER(CLIENT_ID, PRE_ADVICE_ID),
    FOREIGN KEY (CLIENT_ID, SKU_ID) REFERENCES core.SKU(CLIENT_ID, SKU_ID)
);
