CREATE TABLE IF NOT EXISTS core.PRODUCT_CATEGORY (
    CLIENT_ID VARCHAR(30) NOT NULL,
    CATEGORY_CODE VARCHAR(50) NOT NULL,
    PARENT_CATEGORY_CODE VARCHAR(50),
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    SLUG VARCHAR(120) NOT NULL,
    DESCRIPTION VARCHAR(500),
    SORT_SEQUENCE INTEGER NOT NULL DEFAULT 100,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID,CATEGORY_CODE),
    CONSTRAINT FK_PRODUCT_CATEGORY_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID),
    CONSTRAINT UQ_PRODUCT_CATEGORY_SLUG
        UNIQUE (CLIENT_ID,SLUG)
);

COMMENT ON TABLE core.PRODUCT_CATEGORY IS
'Website catalogue category tree. Separate from warehouse SKU grouping.';
