CREATE TABLE IF NOT EXISTS core.PRODUCT_GROUP (
    PRODUCT_GROUP_ID varchar(50) PRIMARY KEY,
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    PARENT_GROUP_ID varchar(50),
    DESCRIPTION varchar(150) NOT NULL,
    DISPLAY_SEQUENCE integer NOT NULL DEFAULT 100,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (PARENT_GROUP_ID) REFERENCES core.PRODUCT_GROUP(PRODUCT_GROUP_ID)
);
