CREATE TABLE IF NOT EXISTS core.PRODUCT (
    CLIENT_ID VARCHAR(30) NOT NULL,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    SLUG VARCHAR(220) NOT NULL,
    BRAND_NAME VARCHAR(100),
    CATEGORY_CODE VARCHAR(50),
    SHORT_DESCRIPTION VARCHAR(500),
    DESCRIPTION TEXT,
    DELIVERY_CLASS VARCHAR(30) NOT NULL DEFAULT 'STANDARD',
    CURRENCY VARCHAR(3) NOT NULL DEFAULT 'GBP',
    MEDIA JSONB NOT NULL DEFAULT '[]'::jsonb,
    SPECIFICATION JSONB NOT NULL DEFAULT '{}'::jsonb,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    FEATURED BOOLEAN NOT NULL DEFAULT FALSE,
    SORT_SEQUENCE INTEGER NOT NULL DEFAULT 100,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID,PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID),
    CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CLIENT_ID,CATEGORY_CODE)
        REFERENCES core.PRODUCT_CATEGORY (CLIENT_ID,CATEGORY_CODE),
    CONSTRAINT UQ_PRODUCT_SLUG
        UNIQUE (CLIENT_ID,SLUG)
);

COMMENT ON TABLE core.PRODUCT IS
'Customer-facing product master. One PRODUCT may expose multiple stock-controlled SKU variants.';
