CREATE TABLE IF NOT EXISTS core.PRODUCT_VARIANT (
    CLIENT_ID VARCHAR(30) NOT NULL,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    SKU_ID VARCHAR(50) NOT NULL,
    VARIANT_NAME VARCHAR(200) NOT NULL,
    OPTION_VALUES JSONB NOT NULL DEFAULT '{}'::jsonb,
    WEB_PRICE NUMERIC(12,2) NOT NULL,
    COMPARE_AT_PRICE NUMERIC(12,2),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    SORT_SEQUENCE INTEGER NOT NULL DEFAULT 100,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID,PRODUCT_ID,SKU_ID),
    CONSTRAINT FK_PRODUCT_VARIANT_PRODUCT
        FOREIGN KEY (CLIENT_ID,PRODUCT_ID)
        REFERENCES core.PRODUCT (CLIENT_ID,PRODUCT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_VARIANT_SKU
        FOREIGN KEY (CLIENT_ID,SKU_ID)
        REFERENCES core.SKU (CLIENT_ID,SKU_ID)
);

COMMENT ON TABLE core.PRODUCT_VARIANT IS
'Maps customer-selectable product options to the real warehouse SKU.';
