CREATE TABLE IF NOT EXISTS core.SITE (
    SITE_ID varchar(30) PRIMARY KEY,
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    DESCRIPTION varchar(120) NOT NULL,
    SITE_TYPE varchar(30) NOT NULL DEFAULT 'FULFILMENT',
    ADDRESS_ID varchar(50),
    TIME_ZONE varchar(80),
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now()
);
