CREATE TABLE IF NOT EXISTS core.SKU_MEDIA (
    MEDIA_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    SKU_ID varchar(50) NOT NULL,
    MEDIA_TYPE varchar(30) NOT NULL,
    MEDIA_ROLE varchar(40),
    FILE_PATH text NOT NULL,
    THUMBNAIL_PATH text,
    POSTER_PATH text,
    ALT_TEXT varchar(250),
    TITLE varchar(250),
    SORT_SEQUENCE integer NOT NULL DEFAULT 100,
    PRIMARY_MEDIA boolean NOT NULL DEFAULT false,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (CLIENT_ID, SKU_ID) REFERENCES core.SKU(CLIENT_ID, SKU_ID)
);
