CREATE TABLE IF NOT EXISTS core.SUPPLIER_SKU (
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    SUPPLIER_ID varchar(50) NOT NULL REFERENCES core.SUPPLIER(SUPPLIER_ID),
    SKU_ID varchar(50) NOT NULL,
    SUPPLIER_SKU_ID varchar(80),
    COST_PRICE numeric(14,4),
    CURRENCY varchar(3),
    LEAD_TIME_DAYS integer,
    MIN_ORDER_QTY numeric(18,6),
    PREFERRED boolean NOT NULL DEFAULT false,
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, SUPPLIER_ID, SKU_ID),
    FOREIGN KEY (CLIENT_ID, SKU_ID) REFERENCES core.SKU(CLIENT_ID, SKU_ID)
);
