CREATE OR REPLACE FUNCTION interface.PROCESS_ORDER_INTERFACE(P_INTERFACE_ID uuid)
RETURNS TABLE (RESULT_STATUS varchar, RESULT_ORDER_ID varchar, RESULT_MESSAGE text)
LANGUAGE plpgsql
AS $$
DECLARE
    V_HEADER interface.ORDER_HEADER_IF%ROWTYPE;
    V_ORDER_ID varchar(20);
    V_NUM_LINES integer;
    V_BAD_SKUS text;
BEGIN
    SELECT * INTO V_HEADER
      FROM interface.ORDER_HEADER_IF
     WHERE INTERFACE_ID = P_INTERFACE_ID
     FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'ERROR'::varchar, NULL::varchar, 'Interface order not found.'::text;
        RETURN;
    END IF;

    IF V_HEADER.PROCESS_STATUS = 'PROCESSED' THEN
        RETURN QUERY SELECT 'PROCESSED'::varchar, V_HEADER.ORDER_ID::varchar,
               'Order has already been processed; no duplicate created.'::text;
        RETURN;
    END IF;

    UPDATE interface.ORDER_HEADER_IF
       SET PROCESS_STATUS='VALIDATING', ERROR_CODE=NULL, ERROR_TEXT=NULL
     WHERE INTERFACE_ID=P_INTERFACE_ID;

    UPDATE interface.ORDER_LINE_IF
       SET PROCESS_STATUS='VALIDATING', ERROR_CODE=NULL, ERROR_TEXT=NULL
     WHERE INTERFACE_ID=P_INTERFACE_ID;

    IF NOT EXISTS (
        SELECT 1 FROM core.CLIENT
         WHERE CLIENT_ID=V_HEADER.CLIENT_ID AND ACTIVE=true
    ) THEN
        RAISE EXCEPTION 'CLIENT_NOT_FOUND: %', V_HEADER.CLIENT_ID;
    END IF;

    SELECT COUNT(*) INTO V_NUM_LINES
      FROM interface.ORDER_LINE_IF
     WHERE INTERFACE_ID=P_INTERFACE_ID;

    IF V_NUM_LINES=0 THEN
        RAISE EXCEPTION 'NO_ORDER_LINES';
    END IF;

    IF EXISTS (
        SELECT 1 FROM interface.ORDER_LINE_IF
         WHERE INTERFACE_ID=P_INTERFACE_ID AND QTY_ORDERED<=0
    ) THEN
        RAISE EXCEPTION 'INVALID_QTY';
    END IF;

    SELECT string_agg(DISTINCT L.SKU_ID, ', ' ORDER BY L.SKU_ID)
      INTO V_BAD_SKUS
      FROM interface.ORDER_LINE_IF L
      LEFT JOIN core.SKU S
        ON S.CLIENT_ID=V_HEADER.CLIENT_ID
       AND S.SKU_ID=L.SKU_ID
     WHERE L.INTERFACE_ID=P_INTERFACE_ID
       AND S.SKU_ID IS NULL;

    IF V_BAD_SKUS IS NOT NULL THEN
        RAISE EXCEPTION 'SKU_NOT_FOUND: %', V_BAD_SKUS;
    END IF;

    V_ORDER_ID := COALESCE(NULLIF(V_HEADER.ORDER_ID,''), LEFT(V_HEADER.SOURCE_ORDER_ID,20));

    IF EXISTS (
        SELECT 1 FROM core.ORDER_HEADER
         WHERE CLIENT_ID=V_HEADER.CLIENT_ID AND ORDER_ID=V_ORDER_ID
    ) THEN
        UPDATE interface.ORDER_HEADER_IF
           SET PROCESS_STATUS='PROCESSED',
               ORDER_ID=V_ORDER_ID,
               PROCESSED_DSTAMP=COALESCE(PROCESSED_DSTAMP,now())
         WHERE INTERFACE_ID=P_INTERFACE_ID;

        UPDATE interface.ORDER_LINE_IF
           SET PROCESS_STATUS='PROCESSED'
         WHERE INTERFACE_ID=P_INTERFACE_ID;

        RETURN QUERY SELECT 'PROCESSED'::varchar, V_ORDER_ID::varchar,
               'Operational order already exists; interface marked processed.'::text;
        RETURN;
    END IF;

    INSERT INTO core.ORDER_HEADER (
        CLIENT_ID, ORDER_ID, STATUS, CUSTOMER_ID, ORDER_DATE,
        SHIP_BY_DATE, DELIVER_BY_DATE, DISPATCH_METHOD, SERVICE_LEVEL,
        ORDER_VALUE, INV_CURRENCY, NUM_LINES, ORDER_SOURCE,
        CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE,
        PAYMENT_STATUS, FULFILMENT_STATUS, FREE_DELIVERY
    )
    VALUES (
        V_HEADER.CLIENT_ID, V_ORDER_ID, 'NEW', V_HEADER.CUSTOMER_ID, V_HEADER.ORDER_DATE,
        V_HEADER.SHIP_BY_DATE, V_HEADER.DELIVER_BY_DATE, V_HEADER.DISPATCH_METHOD,
        V_HEADER.SERVICE_LEVEL, V_HEADER.ORDER_VALUE, V_HEADER.CURRENCY, V_NUM_LINES,
        'I', 'INTERFACE', now(), 'INTERFACE', now(), 'PENDING', 'NEW', 'N'
    );

    INSERT INTO core.ORDER_LINE (
        CLIENT_ID, ORDER_ID, LINE_ID, SKU_ID, QTY_ORDERED,
        PRODUCT_PRICE, EXTENDED_PRICE, PRODUCT_CURRENCY, NOTES,
        ALLOCATE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
    )
    SELECT
        V_HEADER.CLIENT_ID, V_ORDER_ID, L.LINE_ID, L.SKU_ID, L.QTY_ORDERED,
        L.PRODUCT_PRICE, COALESCE(L.EXTENDED_PRICE,L.PRODUCT_PRICE*L.QTY_ORDERED),
        V_HEADER.CURRENCY, L.NOTES, 'Y',
        'INTERFACE', now(), 'INTERFACE', now()
      FROM interface.ORDER_LINE_IF L
     WHERE L.INTERFACE_ID=P_INTERFACE_ID;

    UPDATE interface.ORDER_LINE_IF
       SET PROCESS_STATUS='PROCESSED', ERROR_CODE=NULL, ERROR_TEXT=NULL
     WHERE INTERFACE_ID=P_INTERFACE_ID;

    UPDATE interface.ORDER_HEADER_IF
       SET ORDER_ID=V_ORDER_ID, PROCESS_STATUS='PROCESSED',
           ERROR_CODE=NULL, ERROR_TEXT=NULL, PROCESSED_DSTAMP=now()
     WHERE INTERFACE_ID=P_INTERFACE_ID;

    RETURN QUERY SELECT 'PROCESSED'::varchar, V_ORDER_ID::varchar,
           ('Imported '||V_NUM_LINES||' order line(s).')::text;

EXCEPTION
    WHEN OTHERS THEN
        UPDATE interface.ORDER_HEADER_IF
           SET PROCESS_STATUS='ERROR',
               ERROR_CODE=LEFT(SQLSTATE,50),
               ERROR_TEXT=SQLERRM
         WHERE INTERFACE_ID=P_INTERFACE_ID;

        UPDATE interface.ORDER_LINE_IF
           SET PROCESS_STATUS='ERROR',
               ERROR_CODE=LEFT(SQLSTATE,50),
               ERROR_TEXT=SQLERRM
         WHERE INTERFACE_ID=P_INTERFACE_ID
           AND PROCESS_STATUS<>'PROCESSED';

        RETURN QUERY SELECT 'ERROR'::varchar,
               COALESCE(V_ORDER_ID,V_HEADER.ORDER_ID)::varchar,
               SQLERRM::text;
END;
$$;
