CREATE INDEX IF NOT EXISTS IX_CARRIER_SELECTION_RULE_PRIORITY
ON config.CARRIER_SELECTION_RULE (CLIENT_ID, ACTIVE, PRIORITY);

CREATE INDEX IF NOT EXISTS IX_MERGE_RULE_PRIORITY
ON config.MERGE_RULE (CLIENT_ID, ACTIVE, PRIORITY);

CREATE INDEX IF NOT EXISTS IX_PROCESSING_LOG_PROCESS
ON audit.PROCESSING_LOG (PROCESS_NAME, CREATED_DSTAMP);
