CREATE INDEX IF NOT EXISTS IX_SKU_MEDIA_SKU ON core.SKU_MEDIA (CLIENT_ID, SKU_ID, ACTIVE, SORT_SEQUENCE);
CREATE INDEX IF NOT EXISTS IX_SUPPLIER_SKU_SKU ON core.SUPPLIER_SKU (CLIENT_ID, SKU_ID, ACTIVE);
CREATE INDEX IF NOT EXISTS IX_ORDER_CONTAINER_ORDER ON core.ORDER_CONTAINER (CLIENT_ID, ORDER_ID, STATUS);
CREATE INDEX IF NOT EXISTS IX_PRE_ADVICE_LINE_SKU ON core.PRE_ADVICE_LINE (CLIENT_ID, SKU_ID);
CREATE INDEX IF NOT EXISTS IX_ORDER_HEADER_IF_STATUS ON interface.ORDER_HEADER_IF (PROCESS_STATUS, CREATED_DSTAMP);
CREATE INDEX IF NOT EXISTS IX_CARRIER_SELECTION_CONDITION_RULE ON config.CARRIER_SELECTION_CONDITION (RULE_ID, CONDITION_GROUP, SEQUENCE);
CREATE INDEX IF NOT EXISTS IX_MERGE_RULE_CONDITION_RULE ON config.MERGE_RULE_CONDITION (RULE_ID, CONDITION_GROUP, SEQUENCE);
CREATE INDEX IF NOT EXISTS IX_ALLOCATION_RULE_CLIENT_PRIORITY ON config.ALLOCATION_RULE (CLIENT_ID, ACTIVE, PRIORITY);
CREATE INDEX IF NOT EXISTS IX_RULE_DECISION_LOG_ENTITY ON audit.RULE_DECISION_LOG (ENGINE_NAME, ENTITY_TYPE, ENTITY_ID, CREATED_DSTAMP);

