-- Allocation and availability indexes.

CREATE INDEX IF NOT EXISTS IX_INVENTORY_ALLOCATION_SEARCH
    ON core.INVENTORY (
        CLIENT_ID,
        SKU_ID,
        RECEIPT_DSTAMP,
        KEY
    );

CREATE INDEX IF NOT EXISTS IX_INVENTORY_LOCATION
    ON core.INVENTORY (LOCATION_ID);

CREATE INDEX IF NOT EXISTS IX_ORDER_LINE_ALLOCATION_PENDING
    ON core.ORDER_LINE (
        CLIENT_ID,
        ORDER_ID,
        SKU_ID
    );

CREATE INDEX IF NOT EXISTS IX_ALLOCATION_ORDER_LINE
    ON core.ALLOCATION (
        CLIENT_ID,
        ORDER_ID,
        LINE_ID
    );

CREATE INDEX IF NOT EXISTS IX_ALLOCATION_INVENTORY
    ON core.ALLOCATION (INVENTORY_KEY);
