CREATE INDEX IF NOT EXISTS IX_ALLOCATION_OPEN
    ON core.ALLOCATION (CLIENT_ID, ORDER_ID, LINE_ID, STATUS, ALLOCATION_ID);

CREATE INDEX IF NOT EXISTS IX_PICK_TASK_QUEUE
    ON core.PICK_TASK (STATUS, CLIENT_ID, ORDER_ID, LOCATION_ID, PICK_TASK_ID);

CREATE INDEX IF NOT EXISTS IX_PICK_TASK_ORDER_LINE
    ON core.PICK_TASK (CLIENT_ID, ORDER_ID, LINE_ID);

CREATE INDEX IF NOT EXISTS IX_SHIPPING_MANIFEST_CONTAINER
    ON core.SHIPPING_MANIFEST (CLIENT_ID, CONTAINER_ID, SHIPPED, KEY);

CREATE INDEX IF NOT EXISTS IX_SHIPPING_MANIFEST_PICK_TASK
    ON core.SHIPPING_MANIFEST (PICK_TASK_ID)
    WHERE PICK_TASK_ID IS NOT NULL;
