CREATE INDEX IF NOT EXISTS IX_CARRIER_SERVICE_ACTIVE
    ON config.CARRIER_SERVICE (CLIENT_ID, ACTIVE, SORT_SEQUENCE, CARRIER_ID, SERVICE_LEVEL);

CREATE INDEX IF NOT EXISTS IX_CARRIER_RULE_ACTIVE
    ON config.CARRIER_SELECTION_RULE (CLIENT_ID, ACTIVE, PRIORITY, CARRIER_ID, SERVICE_LEVEL);

CREATE INDEX IF NOT EXISTS IX_CARRIER_CONDITION_RULE
    ON config.CARRIER_SELECTION_CONDITION (RULE_ID, CONDITION_GROUP, SEQUENCE);

CREATE INDEX IF NOT EXISTS IX_CARRIER_RATE_LOOKUP
    ON config.CARRIER_SERVICE_RATE
       (CLIENT_ID, CARRIER_ID, SERVICE_LEVEL, ACTIVE, MIN_WEIGHT_KG, MAX_WEIGHT_KG);

CREATE INDEX IF NOT EXISTS IX_RULE_DECISION_CARRIER_ENTITY
    ON audit.RULE_DECISION_LOG (CLIENT_ID, ENGINE_NAME, ENTITY_TYPE, ENTITY_ID, CREATED_DSTAMP);

CREATE INDEX IF NOT EXISTS IX_ORDER_CONTAINER_CARRIER_SELECTION
    ON core.ORDER_CONTAINER (CLIENT_ID, STATUS, CARRIER_ID, SERVICE_LEVEL);
