CREATE INDEX IF NOT EXISTS IX_ORDER_HEADER_FULFILMENT_PREFERENCE
    ON core.ORDER_HEADER
       (CLIENT_ID, FULFILMENT_PREFERENCE, FULFILMENT_STATUS);

CREATE INDEX IF NOT EXISTS IX_ORDER_CONTAINER_HOLD
    ON core.ORDER_CONTAINER
       (CLIENT_ID, HOLD_STATUS, DELIVERY_CLASS, FULFILMENT_METHOD, STATUS);

CREATE INDEX IF NOT EXISTS IX_DELIVERY_CLASS_CONTROL
    ON config.DELIVERY_CLASS_CONTROL
       (CLIENT_ID, DELIVERY_CLASS, CARRIER_DESPATCH_ENABLED);
