CREATE INDEX IF NOT EXISTS IX_MERGE_RULE_ACTIVE
    ON config.MERGE_RULE (CLIENT_ID,ACTIVE,PRIORITY,RULE_ID);

CREATE INDEX IF NOT EXISTS IX_MERGE_CONDITION_RULE
    ON config.MERGE_RULE_CONDITION
       (RULE_ID,CONDITION_GROUP,SEQUENCE,CONDITION_ID);

CREATE INDEX IF NOT EXISTS IX_ORDER_CONTAINER_MERGE_STATUS
    ON core.ORDER_CONTAINER
       (CLIENT_ID,ORDER_ID,STATUS,DELIVERY_CLASS,FULFILMENT_METHOD,HOLD_STATUS);

CREATE INDEX IF NOT EXISTS IX_ORDER_CONTAINER_MERGED_INTO
    ON core.ORDER_CONTAINER
       (CLIENT_ID,MERGED_INTO_CONTAINER_ID);
