CREATE INDEX IF NOT EXISTS IX_PRODUCT_CATEGORY_ACTIVE
    ON core.PRODUCT_CATEGORY (CLIENT_ID,ACTIVE,SORT_SEQUENCE);

CREATE INDEX IF NOT EXISTS IX_PRODUCT_ACTIVE
    ON core.PRODUCT (CLIENT_ID,ACTIVE,FEATURED,SORT_SEQUENCE);

CREATE INDEX IF NOT EXISTS IX_PRODUCT_CATEGORY_LOOKUP
    ON core.PRODUCT (CLIENT_ID,CATEGORY_CODE,ACTIVE);

CREATE INDEX IF NOT EXISTS IX_PRODUCT_VARIANT_ACTIVE
    ON core.PRODUCT_VARIANT (CLIENT_ID,PRODUCT_ID,ACTIVE,SORT_SEQUENCE);
