CREATE INDEX IF NOT EXISTS IX_ORDER_HEADER_IF_WEBSITE_SOURCE
    ON interface.ORDER_HEADER_IF (
        CLIENT_ID,SOURCE_SYSTEM,SOURCE_ORDER_ID,PROCESS_STATUS
    );

CREATE INDEX IF NOT EXISTS IX_ORDER_HEADER_WEB_STATUS
    ON core.ORDER_HEADER (
        CLIENT_ID,ORDER_ID,PAYMENT_STATUS,FULFILMENT_STATUS
    );
