CREATE INDEX IF NOT EXISTS IX_PRODUCT_SEARCH_ALIAS_TEXT ON core.PRODUCT_SEARCH_ALIAS (CLIENT_ID,lower(ALIAS_TEXT)) WHERE ACTIVE=TRUE;
CREATE INDEX IF NOT EXISTS IX_PRODUCT_MEDIA_LOOKUP ON core.PRODUCT_MEDIA (CLIENT_ID,PRODUCT_ID,ACTIVE,SORT_SEQUENCE);
CREATE INDEX IF NOT EXISTS IX_CUSTOMER_INTEREST_ACTIVE ON core.CUSTOMER_INTEREST (CLIENT_ID,SKU_ID,STATUS,INTEREST_TYPE);
CREATE INDEX IF NOT EXISTS IX_STOCK_RESERVATION_EXPIRY ON core.STOCK_RESERVATION (CLIENT_ID,STATUS,EXPIRES_DSTAMP);
CREATE INDEX IF NOT EXISTS IX_AFFILIATE_LINK_PRODUCT ON core.PRODUCT_AFFILIATE_LINK (CLIENT_ID,PRODUCT_ID,ACTIVE);
CREATE INDEX IF NOT EXISTS IX_AFFILIATE_CLICK_LINK ON audit.AFFILIATE_CLICK (CLIENT_ID,LINK_ID,CREATED_DSTAMP);
CREATE INDEX IF NOT EXISTS IX_DELIVERY_ZONE_MATCH ON config.DELIVERY_ZONE (CLIENT_ID,ACTIVE,COUNTRY,PRIORITY);
CREATE INDEX IF NOT EXISTS IX_PRODUCT_REVIEW_PUBLIC ON core.PRODUCT_REVIEW (CLIENT_ID,PRODUCT_ID,STATUS,PUBLISHED_DSTAMP);
CREATE INDEX IF NOT EXISTS IX_PAYMENT_REFERENCE ON core.PAYMENT_TRANSACTION (CLIENT_ID,REFERENCE_TYPE,REFERENCE_ID,STATUS);
