CREATE INDEX IF NOT EXISTS IX_ORDER_HEADER_ACCOUNT
    ON core.ORDER_HEADER (CLIENT_ID,ACCOUNT_ID,ORDER_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_CUSTOMER_INTEREST_ACCOUNT
    ON core.CUSTOMER_INTEREST (CLIENT_ID,ACCOUNT_ID,STATUS,CREATED_DSTAMP DESC);

CREATE INDEX IF NOT EXISTS IX_STOCK_RESERVATION_ACCOUNT
    ON core.STOCK_RESERVATION (CLIENT_ID,ACCOUNT_ID,STATUS,CREATED_DSTAMP DESC);

CREATE INDEX IF NOT EXISTS IX_PAYMENT_TRANSACTION_REFERENCE
    ON core.PAYMENT_TRANSACTION (CLIENT_ID,REFERENCE_TYPE,REFERENCE_ID,CREATED_DSTAMP DESC);

CREATE INDEX IF NOT EXISTS IX_PAYMENT_TRANSACTION_ACCOUNT
    ON core.PAYMENT_TRANSACTION (CLIENT_ID,ACCOUNT_ID,CREATED_DSTAMP DESC);

CREATE INDEX IF NOT EXISTS IX_PAYMENT_EVENT_PROVIDER_REFERENCE
    ON audit.PAYMENT_EVENT (CLIENT_ID,PROVIDER,PROVIDER_REFERENCE,CREATED_DSTAMP DESC);

CREATE INDEX IF NOT EXISTS IX_API_SECURITY_EVENT_CREATED
    ON audit.API_SECURITY_EVENT (CREATED_DSTAMP DESC);
