-- 0007_add_allocation.sql
-- Existing-database migration for Allocation V1.
--
-- Clean-build safe and re-runnable:
--   * only changes KEY data types when conversion is actually required
--   * avoids PostgreSQL view dependency errors on already-upgraded databases
--   * creates core.ALLOCATION using the canonical Allocation V1 structure
--     expected by database/tables/core/ALLOCATION.sql
--
-- Warehouse Execution V1 extends this table later in migration 0008.

BEGIN;

-- INVENTORY.KEY -------------------------------------------------------------

DO $$
DECLARE
    v_data_type text;
BEGIN
    SELECT c.data_type
      INTO v_data_type
      FROM information_schema.columns c
     WHERE c.table_schema = 'core'
       AND c.table_name = 'inventory'
       AND c.column_name = 'key';

    IF v_data_type IS NULL THEN
        RAISE EXCEPTION 'core.INVENTORY.KEY does not exist';
    END IF;

    IF v_data_type <> 'bigint' THEN
        -- A previously-built database may already have this view.
        -- The allocation build recreates it after this migration.
        DROP VIEW IF EXISTS core.INVENTORY_AVAILABILITY;

        ALTER TABLE core.INVENTORY
            ALTER COLUMN KEY TYPE BIGINT
            USING KEY::BIGINT;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'core'
           AND table_name = 'inventory'
           AND column_name = 'key'
           AND is_identity = 'NO'
    ) THEN
        ALTER TABLE core.INVENTORY
            ALTER COLUMN KEY ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

DO $$
DECLARE
    v_seq text;
    v_next bigint;
BEGIN
    v_seq := pg_get_serial_sequence('core.inventory', 'key');

    IF v_seq IS NOT NULL THEN
        SELECT COALESCE(MAX(KEY), 0) + 1
          INTO v_next
          FROM core.INVENTORY;

        PERFORM setval(v_seq, v_next, false);
    END IF;
END
$$;

-- INVENTORY_TRANSACTION.KEY -------------------------------------------------

DO $$
DECLARE
    v_data_type text;
BEGIN
    SELECT c.data_type
      INTO v_data_type
      FROM information_schema.columns c
     WHERE c.table_schema = 'core'
       AND c.table_name = 'inventory_transaction'
       AND c.column_name = 'key';

    IF v_data_type IS NULL THEN
        RAISE EXCEPTION 'core.INVENTORY_TRANSACTION.KEY does not exist';
    END IF;

    IF v_data_type <> 'bigint' THEN
        ALTER TABLE core.INVENTORY_TRANSACTION
            ALTER COLUMN KEY TYPE BIGINT
            USING KEY::BIGINT;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'core'
           AND table_name = 'inventory_transaction'
           AND column_name = 'key'
           AND is_identity = 'NO'
    ) THEN
        ALTER TABLE core.INVENTORY_TRANSACTION
            ALTER COLUMN KEY ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

DO $$
DECLARE
    v_seq text;
    v_next bigint;
BEGIN
    v_seq := pg_get_serial_sequence('core.inventory_transaction', 'key');

    IF v_seq IS NOT NULL THEN
        SELECT COALESCE(MAX(KEY), 0) + 1
          INTO v_next
          FROM core.INVENTORY_TRANSACTION;

        PERFORM setval(v_seq, v_next, false);
    END IF;
END
$$;

-- Canonical Allocation V1 table --------------------------------------------
-- Keep this definition aligned with database/tables/core/ALLOCATION.sql.
-- Migration 0008 adds Warehouse Execution columns such as QTY_PICKED,
-- QTY_RELEASED, STATUS and LAST_UPDATE_DSTAMP.

CREATE TABLE IF NOT EXISTS core.ALLOCATION (
    ALLOCATION_ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CLIENT_ID                      VARCHAR(10) NOT NULL,
    ORDER_ID                       VARCHAR(20) NOT NULL,
    LINE_ID                        NUMERIC(6) NOT NULL,
    INVENTORY_KEY                  BIGINT NOT NULL,
    QTY_ALLOCATED                  NUMERIC(15,6) NOT NULL,
    ALLOCATION_DSTAMP              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CREATED_BY                     VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',

    PRIMARY KEY (ALLOCATION_ID),

    FOREIGN KEY (CLIENT_ID, ORDER_ID, LINE_ID)
        REFERENCES core.ORDER_LINE (CLIENT_ID, ORDER_ID, LINE_ID),

    FOREIGN KEY (INVENTORY_KEY)
        REFERENCES core.INVENTORY (KEY),

    CONSTRAINT CK_ALLOCATION_QTY_POSITIVE
        CHECK (QTY_ALLOCATED > 0)
);

COMMIT;
