BEGIN;

-- Preserve allocation history once picking starts.
ALTER TABLE core.ALLOCATION
    ADD COLUMN IF NOT EXISTS QTY_PICKED NUMERIC(15,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS QTY_RELEASED NUMERIC(15,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS STATUS VARCHAR(30) NOT NULL DEFAULT 'ALLOCATED',
    ADD COLUMN IF NOT EXISTS LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS LAST_UPDATED_BY VARCHAR(20) NOT NULL DEFAULT 'SYSTEM';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_allocation_qty_consumed'
          AND conrelid = 'core.allocation'::regclass
    ) THEN
        ALTER TABLE core.ALLOCATION
            ADD CONSTRAINT CK_ALLOCATION_QTY_CONSUMED
            CHECK (QTY_PICKED >= 0 AND QTY_RELEASED >= 0 AND QTY_PICKED + QTY_RELEASED <= QTY_ALLOCATED);
    END IF;
END
$$;

-- Inventory transactions and shipping manifest rows are created by execution
-- functions, so both keys need a safe PostgreSQL generator.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='core' AND table_name='inventory_transaction' AND column_name='key'
          AND data_type <> 'bigint'
    ) THEN
        ALTER TABLE core.INVENTORY_TRANSACTION ALTER COLUMN KEY TYPE BIGINT;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='core' AND table_name='shipping_manifest' AND column_name='key'
          AND data_type <> 'bigint'
    ) THEN
        ALTER TABLE core.SHIPPING_MANIFEST ALTER COLUMN KEY TYPE BIGINT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'core' AND table_name = 'inventory_transaction'
          AND column_name = 'key' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE core.INVENTORY_TRANSACTION
            ALTER COLUMN KEY ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'core' AND table_name = 'shipping_manifest'
          AND column_name = 'key' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE core.SHIPPING_MANIFEST
            ALTER COLUMN KEY ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$;

SELECT setval(
    pg_get_serial_sequence('core.inventory_transaction', 'key'),
    COALESCE(MAX(KEY), 1),
    COUNT(*) > 0
)
FROM core.INVENTORY_TRANSACTION;

SELECT setval(
    pg_get_serial_sequence('core.shipping_manifest', 'key'),
    COALESCE(MAX(KEY), 1),
    COUNT(*) > 0
)
FROM core.SHIPPING_MANIFEST;

CREATE TABLE IF NOT EXISTS core.PICK_TASK (
    PICK_TASK_ID             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLIENT_ID                VARCHAR(10) NOT NULL,
    ORDER_ID                 VARCHAR(20) NOT NULL,
    LINE_ID                  NUMERIC(6) NOT NULL,
    ALLOCATION_ID            BIGINT NOT NULL,
    INVENTORY_KEY            BIGINT NOT NULL,
    SKU_ID                   VARCHAR(50) NOT NULL,
    LOCATION_ID              VARCHAR(20) NOT NULL,
    BATCH_ID                 VARCHAR(50),
    QTY_REQUIRED             NUMERIC(15,6) NOT NULL,
    QTY_PICKED               NUMERIC(15,6) NOT NULL DEFAULT 0,
    SHORT_QTY                NUMERIC(15,6) NOT NULL DEFAULT 0,
    STATUS                   VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    SHORT_REASON             VARCHAR(120),
    CREATED_DSTAMP           TIMESTAMPTZ NOT NULL DEFAULT now(),
    STARTED_DSTAMP           TIMESTAMPTZ,
    COMPLETED_DSTAMP         TIMESTAMPTZ,
    LAST_UPDATE_DSTAMP       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CREATED_BY               VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    LAST_UPDATED_BY          VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    CONSTRAINT UQ_PICK_TASK_ALLOCATION UNIQUE (ALLOCATION_ID),
    CONSTRAINT FK_PICK_TASK_ORDER_LINE FOREIGN KEY (CLIENT_ID, ORDER_ID, LINE_ID)
        REFERENCES core.ORDER_LINE (CLIENT_ID, ORDER_ID, LINE_ID),
    CONSTRAINT FK_PICK_TASK_ALLOCATION FOREIGN KEY (ALLOCATION_ID)
        REFERENCES core.ALLOCATION (ALLOCATION_ID),
    CONSTRAINT FK_PICK_TASK_INVENTORY FOREIGN KEY (INVENTORY_KEY)
        REFERENCES core.INVENTORY (KEY),
    CONSTRAINT FK_PICK_TASK_SKU FOREIGN KEY (CLIENT_ID, SKU_ID)
        REFERENCES core.SKU (CLIENT_ID, SKU_ID),
    CONSTRAINT FK_PICK_TASK_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES core.LOCATION (LOCATION_ID),
    CONSTRAINT CK_PICK_TASK_QTY CHECK (
        QTY_REQUIRED > 0 AND QTY_PICKED >= 0 AND SHORT_QTY >= 0
        AND QTY_PICKED + SHORT_QTY <= QTY_REQUIRED
    )
);

ALTER TABLE core.SHIPPING_MANIFEST
    ADD COLUMN IF NOT EXISTS PICK_TASK_ID BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_shipping_manifest_pick_task'
          AND conrelid = 'core.shipping_manifest'::regclass
    ) THEN
        ALTER TABLE core.SHIPPING_MANIFEST
            ADD CONSTRAINT FK_SHIPPING_MANIFEST_PICK_TASK
            FOREIGN KEY (PICK_TASK_ID) REFERENCES core.PICK_TASK (PICK_TASK_ID);
    END IF;
END
$$;

COMMIT;
