BEGIN;

CREATE TABLE IF NOT EXISTS config.CARRIER_SERVICE_RATE (
    RATE_ID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID                VARCHAR(30) NOT NULL,
    CARRIER_ID               VARCHAR(30) NOT NULL,
    SERVICE_LEVEL            VARCHAR(50) NOT NULL,
    MIN_WEIGHT_KG            NUMERIC(12,3) NOT NULL DEFAULT 0,
    MAX_WEIGHT_KG            NUMERIC(12,3),
    POSTCODE_PREFIX          VARCHAR(20),
    COUNTRY_CODE             VARCHAR(3),
    BASE_COST                NUMERIC(12,2) NOT NULL DEFAULT 0,
    COST_PER_KG              NUMERIC(12,4) NOT NULL DEFAULT 0,
    SURCHARGE                NUMERIC(12,2) NOT NULL DEFAULT 0,
    ACTIVE                   BOOLEAN NOT NULL DEFAULT TRUE,
    PRIORITY                 INTEGER NOT NULL DEFAULT 100,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    CREATED_DSTAMP           TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP      TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (CLIENT_ID, CARRIER_ID, SERVICE_LEVEL)
        REFERENCES config.CARRIER_SERVICE (CLIENT_ID, CARRIER_ID, SERVICE_LEVEL)
);

-- Carrier selection result belongs to the physical order container.
ALTER TABLE core.ORDER_CONTAINER
    ADD COLUMN IF NOT EXISTS DELIVERY_CLASS VARCHAR(30),
    ADD COLUMN IF NOT EXISTS CARRIER_COST NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS CARRIER_SELECTION_SOURCE VARCHAR(30),
    ADD COLUMN IF NOT EXISTS CARRIER_SELECTION_RULE_ID BIGINT,
    ADD COLUMN IF NOT EXISTS CARRIER_SELECTED_DSTAMP TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS CARRIER_OVERRIDE_REASON VARCHAR(250);

-- Keep manifest lines synchronized with the selected container service.
ALTER TABLE core.SHIPPING_MANIFEST
    ADD COLUMN IF NOT EXISTS CARRIER_SELECTION_RULE_ID BIGINT;

COMMIT;
