BEGIN;

ALTER TABLE core.ORDER_HEADER
    ADD COLUMN IF NOT EXISTS FULFILMENT_PREFERENCE VARCHAR(30)
        NOT NULL DEFAULT 'CONSOLIDATE';

ALTER TABLE core.ORDER_CONTAINER
    ADD COLUMN IF NOT EXISTS FULFILMENT_METHOD VARCHAR(30),
    ADD COLUMN IF NOT EXISTS HOLD_STATUS VARCHAR(30)
        NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS HOLD_REASON VARCHAR(250),
    ADD COLUMN IF NOT EXISTS HOLD_DSTAMP TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS HOLD_SOURCE VARCHAR(30),
    ADD COLUMN IF NOT EXISTS RELEASE_DSTAMP TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS RELEASED_BY VARCHAR(20);

-- Purpose-built generic delivery-class control.
-- This avoids coupling despatch safety policy to the unrelated FEATURE_FLAG schema.
CREATE TABLE IF NOT EXISTS config.DELIVERY_CLASS_CONTROL (
    CLIENT_ID VARCHAR(30) NOT NULL,
    DELIVERY_CLASS VARCHAR(30) NOT NULL,
    CARRIER_DESPATCH_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    HOLD_REASON VARCHAR(250),
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, DELIVERY_CLASS),
    CONSTRAINT FK_DELIVERY_CLASS_CONTROL_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID)
);

-- Seed LIVESTOCK control for every existing client.
INSERT INTO config.DELIVERY_CLASS_CONTROL (
    CLIENT_ID,
    DELIVERY_CLASS,
    CARRIER_DESPATCH_ENABLED,
    HOLD_REASON
)
SELECT
    c.CLIENT_ID,
    'LIVESTOCK',
    TRUE,
    NULL
FROM core.CLIENT c
ON CONFLICT (CLIENT_ID, DELIVERY_CLASS) DO NOTHING;

COMMIT;
