BEGIN;

CREATE TABLE IF NOT EXISTS config.MERGE_RULE (
    RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID VARCHAR(30) NOT NULL,
    RULE_NAME VARCHAR(100) NOT NULL,
    PRIORITY INTEGER NOT NULL DEFAULT 100,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DECISION VARCHAR(10) NOT NULL DEFAULT 'ALLOW',
    STOP_ON_MATCH BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT FK_MERGE_RULE_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID),
    CONSTRAINT CK_MERGE_RULE_DECISION
        CHECK (DECISION IN ('ALLOW','DENY')),
    CONSTRAINT UQ_MERGE_RULE_NAME
        UNIQUE (CLIENT_ID, RULE_NAME)
);

CREATE TABLE IF NOT EXISTS config.MERGE_RULE_CONDITION (
    CONDITION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_ID BIGINT NOT NULL,
    FIELD_NAME VARCHAR(50) NOT NULL,
    OPERATOR VARCHAR(20) NOT NULL,
    VALUE_TEXT VARCHAR(250),
    VALUE_NUMERIC NUMERIC(18,4),
    VALUE_BOOLEAN BOOLEAN,
    VALUE_FROM NUMERIC(18,4),
    VALUE_TO NUMERIC(18,4),
    CONDITION_GROUP INTEGER NOT NULL DEFAULT 1,
    SEQUENCE INTEGER NOT NULL DEFAULT 10,
    NEGATE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT FK_MERGE_CONDITION_RULE
        FOREIGN KEY (RULE_ID)
        REFERENCES config.MERGE_RULE (RULE_ID)
        ON DELETE CASCADE
);

ALTER TABLE core.ORDER_CONTAINER
    ADD COLUMN IF NOT EXISTS MERGED_INTO_CONTAINER_ID VARCHAR(80),
    ADD COLUMN IF NOT EXISTS MERGED_DSTAMP TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS MERGED_BY VARCHAR(20),
    ADD COLUMN IF NOT EXISTS MERGE_RULE_ID BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname='fk_order_container_merge_rule'
    ) THEN
        ALTER TABLE core.ORDER_CONTAINER
            ADD CONSTRAINT FK_ORDER_CONTAINER_MERGE_RULE
            FOREIGN KEY (MERGE_RULE_ID)
            REFERENCES config.MERGE_RULE (RULE_ID);
    END IF;
END
$$;

COMMIT;
