BEGIN;

UPDATE config.SYSTEM_VERSION
   SET IS_CURRENT = FALSE
 WHERE PRODUCT_CODE = 'DYNETIC_WMS'
   AND IS_CURRENT = TRUE
   AND VERSION_NUMBER <> '0.3.4';

INSERT INTO config.SYSTEM_VERSION (
    PRODUCT_CODE,
    PRODUCT_NAME,
    VERSION_NUMBER,
    VERSION_MAJOR,
    VERSION_MINOR,
    VERSION_PATCH,
    BUILD_NUMBER,
    RELEASE_CHANNEL,
    RELEASE_DATE,
    DESCRIPTION,
    IS_CURRENT
)
VALUES (
    'DYNETIC_WMS',
    'DYNETIC WMS',
    '0.3.4',
    0,
    3,
    4,
    0,
    'RELEASE',
    CURRENT_DATE,
    'Validated checkout and address handling, authoritative fulfilment pricing, collision-safe web order IDs, FINatics fry-tray media, and fail-closed production deployment controls.',
    TRUE
)
ON CONFLICT (PRODUCT_CODE, VERSION_NUMBER)
DO UPDATE SET
    PRODUCT_NAME = EXCLUDED.PRODUCT_NAME,
    VERSION_MAJOR = EXCLUDED.VERSION_MAJOR,
    VERSION_MINOR = EXCLUDED.VERSION_MINOR,
    VERSION_PATCH = EXCLUDED.VERSION_PATCH,
    BUILD_NUMBER = EXCLUDED.BUILD_NUMBER,
    RELEASE_CHANNEL = EXCLUDED.RELEASE_CHANNEL,
    RELEASE_DATE = EXCLUDED.RELEASE_DATE,
    DESCRIPTION = EXCLUDED.DESCRIPTION,
    IS_CURRENT = TRUE;

COMMIT;
