BEGIN;

CREATE TABLE IF NOT EXISTS core.PAYMENT_CUSTOMER (
    PAYMENT_CUSTOMER_ID      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLIENT_ID                VARCHAR(30) NOT NULL,
    PROVIDER                 VARCHAR(30) NOT NULL,
    EMAIL                    VARCHAR(254) NOT NULL,
    CUSTOMER_NAME            VARCHAR(200),
    ACCOUNT_ID               UUID,
    PROVIDER_CUSTOMER_ID     VARCHAR(200) NOT NULL,
    CREATED_DSTAMP           TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT FK_PAYMENT_CUSTOMER_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT(CLIENT_ID),

    CONSTRAINT FK_PAYMENT_CUSTOMER_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES core.CUSTOMER_ACCOUNT(ACCOUNT_ID),

    CONSTRAINT CK_PAYMENT_CUSTOMER_PROVIDER
        CHECK (PROVIDER IN ('STRIPE','PAYPAL'))
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_PAYMENT_CUSTOMER_EMAIL
    ON core.PAYMENT_CUSTOMER
       (CLIENT_ID,PROVIDER,LOWER(EMAIL));

CREATE UNIQUE INDEX IF NOT EXISTS UQ_PAYMENT_CUSTOMER_PROVIDER_ID
    ON core.PAYMENT_CUSTOMER
       (CLIENT_ID,PROVIDER,PROVIDER_CUSTOMER_ID);

CREATE INDEX IF NOT EXISTS IX_PAYMENT_CUSTOMER_ACCOUNT
    ON core.PAYMENT_CUSTOMER
       (CLIENT_ID,ACCOUNT_ID);

DO $$
DECLARE
    v_app_role name;
BEGIN
    SELECT pg_get_userbyid(nspowner)
      INTO v_app_role
      FROM pg_namespace
     WHERE nspname='core';

    IF v_app_role IS NULL THEN
        RAISE EXCEPTION 'CORE_SCHEMA_OWNER_NOT_FOUND';
    END IF;

    EXECUTE format(
        'GRANT SELECT,INSERT,UPDATE ON core.payment_customer TO %I',
        v_app_role
    );
END
$$;

COMMIT;
