-- DYNETIC WMS 0.3.18 release registration
-- Applied after the 0.3.18 structural/runtime migrations.

BEGIN;

UPDATE config.SYSTEM_VERSION
   SET IS_CURRENT=FALSE
 WHERE PRODUCT_CODE='DYNETIC_WMS'
   AND IS_CURRENT=TRUE
   AND VERSION_NUMBER <> '0.3.18';

INSERT INTO config.SYSTEM_VERSION (
    PRODUCT_CODE,
    PRODUCT_NAME,
    VERSION_NUMBER,
    VERSION_MAJOR,
    VERSION_MINOR,
    VERSION_PATCH,
    BUILD_NUMBER,
    RELEASE_CHANNEL,
    RELEASE_DATE,
    DESCRIPTION,
    IS_CURRENT
)
VALUES (
    'DYNETIC_WMS',
    'DYNETIC WMS',
    '0.3.18',
    0,
    3,
    18,
    0,
    'RELEASE',
    CURRENT_DATE,
    'Multi-site operational foundation, authoritative order numbering, expanded Generic Admin operations, audit filtering, product maintenance and item-level returns/claims.',
    TRUE
)
ON CONFLICT (PRODUCT_CODE, VERSION_NUMBER)
DO UPDATE SET
    PRODUCT_NAME=EXCLUDED.PRODUCT_NAME,
    VERSION_MAJOR=EXCLUDED.VERSION_MAJOR,
    VERSION_MINOR=EXCLUDED.VERSION_MINOR,
    VERSION_PATCH=EXCLUDED.VERSION_PATCH,
    BUILD_NUMBER=EXCLUDED.BUILD_NUMBER,
    RELEASE_CHANNEL=EXCLUDED.RELEASE_CHANNEL,
    RELEASE_DATE=EXCLUDED.RELEASE_DATE,
    DESCRIPTION=EXCLUDED.DESCRIPTION,
    IS_CURRENT=TRUE;

COMMIT;
