\set ON_ERROR_STOP on

-- DYNETIC_TEST_ENVIRONMENT_GUARD_BEGIN
DO $dynetic_test_guard$
DECLARE
    v_database text := current_database();
BEGIN
    IF v_database NOT IN ('fulfilment_dev', 'fulfilment_test') THEN
        RAISE EXCEPTION
            'SAFETY STOP: database test execution is forbidden against database "%". Only fulfilment_dev and fulfilment_test are allowed.',
            v_database;
    END IF;

    RAISE NOTICE 'SAFETY: test database verified as %', v_database;
END
$dynetic_test_guard$;
-- DYNETIC_TEST_ENVIRONMENT_GUARD_END
BEGIN;

INSERT INTO core.CLIENT (CLIENT_ID,DESCRIPTION,ACTIVE) VALUES ('WHV1TEST','Warehouse V1 Test',true)
ON CONFLICT (CLIENT_ID) DO NOTHING;
INSERT INTO core.SKU (CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES ('WHV1TEST','WH-SKU-001','Warehouse execution SKU','N','N','N','N','N')
ON CONFLICT (CLIENT_ID,SKU_ID) DO NOTHING;
INSERT INTO core.LOCATION (LOCATION_ID,LOC_TYPE,LOCK_STATUS,VOLUME,COUNT_NEEDED,ID,DESCRIPTION,ACTIVE,LIVESTOCK_ALLOWED,DISALLOW_ALLOC)
VALUES ('WH-LOC-01','STORAGE','UNLOCKED',100,'N',910001,'Warehouse V1 loc 1','Y','Y','N'),
       ('WH-LOC-02','STORAGE','UNLOCKED',100,'N',910002,'Warehouse V1 loc 2','Y','Y','N')
ON CONFLICT (LOCATION_ID) DO NOTHING;

INSERT INTO core.INVENTORY (CLIENT_ID,SKU_ID,LOCATION_ID,QTY_ON_HAND,QTY_ALLOCATED,LOCK_STATUS,RECEIPT_DSTAMP,MOVE_DSTAMP,DISALLOW_ALLOC,DESCRIPTION)
VALUES ('WHV1TEST','WH-SKU-001','WH-LOC-01',3,0,'UNLOCKED',now()-interval '10 days',now(),'N','WH lifecycle old stock'),
       ('WHV1TEST','WH-SKU-001','WH-LOC-02',10,0,'UNLOCKED',now()-interval '1 day',now(),'N','WH lifecycle new stock');

INSERT INTO core.ORDER_HEADER (CLIENT_ID,ORDER_ID,ORDER_DATE,CUSTOMER_ID,FREE_DELIVERY,FULFILMENT_STATUS)
VALUES ('WHV1TEST','WH-ORDER-001',now(),'WH-CUST','N','NEW');
INSERT INTO core.ORDER_LINE (CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES ('WHV1TEST','WH-ORDER-001',1,'WH-SKU-001',5,0,0,0,'Y');

SELECT * FROM core.ALLOCATE_ORDER('WHV1TEST','WH-ORDER-001');
SELECT * FROM core.CREATE_PICK_TASKS('WHV1TEST','WH-ORDER-001','TEST');

DO $$
DECLARE r RECORD;
BEGIN
    IF (SELECT COUNT(*) FROM core.PICK_TASK WHERE CLIENT_ID='WHV1TEST' AND ORDER_ID='WH-ORDER-001') <> 2 THEN
        RAISE EXCEPTION 'Warehouse lifecycle: expected 2 FIFO pick tasks';
    END IF;
    FOR r IN SELECT PICK_TASK_ID,QTY_REQUIRED FROM core.PICK_TASK WHERE CLIENT_ID='WHV1TEST' AND ORDER_ID='WH-ORDER-001' ORDER BY PICK_TASK_ID
    LOOP
        PERFORM * FROM core.CONFIRM_PICK(r.PICK_TASK_ID,r.QTY_REQUIRED,'TESTER','TEST-STATION',false,NULL);
    END LOOP;
END
$$;

DO $$
DECLARE v_onhand NUMERIC; v_alloc NUMERIC; v_picked NUMERIC; v_tx INTEGER; v_bad INTEGER;
BEGIN
    SELECT SUM(QTY_ON_HAND),SUM(QTY_ALLOCATED) INTO v_onhand,v_alloc FROM core.INVENTORY WHERE CLIENT_ID='WHV1TEST' AND SKU_ID='WH-SKU-001';
    SELECT QTY_PICKED INTO v_picked FROM core.ORDER_LINE WHERE CLIENT_ID='WHV1TEST' AND ORDER_ID='WH-ORDER-001' AND LINE_ID=1;
    SELECT COUNT(*) INTO v_tx FROM core.INVENTORY_TRANSACTION WHERE CLIENT_ID='WHV1TEST' AND REFERENCE_ID='WH-ORDER-001' AND CODE='PICK';
    SELECT COUNT(*) INTO v_bad FROM core.INVENTORY_RESERVATION_RECONCILIATION WHERE CLIENT_ID='WHV1TEST' AND RECONCILIATION_STATUS<>'OK';
    IF v_onhand<>8 OR v_alloc<>0 OR v_picked<>5 OR v_tx<>2 OR v_bad<>0 THEN
        RAISE EXCEPTION 'Warehouse lifecycle pick validation failed: onhand %, alloc %, picked %, tx %, recon %',v_onhand,v_alloc,v_picked,v_tx,v_bad;
    END IF;
END
$$;

SELECT * FROM core.PACK_ORDER('WHV1TEST','WH-ORDER-001','WH-CONT-001','TESTER','PACK-01');
DO $$
BEGIN
    IF (SELECT COALESCE(SUM(QTY_PICKED),0) FROM core.SHIPPING_MANIFEST WHERE CLIENT_ID='WHV1TEST' AND CONTAINER_ID='WH-CONT-001')<>5 THEN
        RAISE EXCEPTION 'Warehouse lifecycle: packed quantity should be 5';
    END IF;
    IF (SELECT STATUS FROM core.ORDER_CONTAINER WHERE CLIENT_ID='WHV1TEST' AND CONTAINER_ID='WH-CONT-001')<>'PACKED' THEN
        RAISE EXCEPTION 'Warehouse lifecycle: container should be PACKED';
    END IF;
END
$$;

SELECT * FROM core.SHIP_CONTAINER('WHV1TEST','WH-CONT-001','TESTER','DESPATCH-01');
DO $$
BEGIN
    IF (SELECT QTY_SHIPPED FROM core.ORDER_LINE WHERE CLIENT_ID='WHV1TEST' AND ORDER_ID='WH-ORDER-001' AND LINE_ID=1)<>5 THEN
        RAISE EXCEPTION 'Warehouse lifecycle: shipped quantity should be 5';
    END IF;
    IF (SELECT FULFILMENT_STATUS FROM core.ORDER_HEADER WHERE CLIENT_ID='WHV1TEST' AND ORDER_ID='WH-ORDER-001')<>'SHIPPED' THEN
        RAISE EXCEPTION 'Warehouse lifecycle: order should be SHIPPED';
    END IF;
    IF EXISTS (SELECT 1 FROM core.SHIPPING_MANIFEST WHERE CLIENT_ID='WHV1TEST' AND CONTAINER_ID='WH-CONT-001' AND SHIPPED<>'Y') THEN
        RAISE EXCEPTION 'Warehouse lifecycle: all manifest rows should be shipped';
    END IF;
END
$$;

ROLLBACK;
\echo 'Warehouse execution full lifecycle test passed.'
