\set ON_ERROR_STOP on

-- DYNETIC_TEST_ENVIRONMENT_GUARD_BEGIN
DO $dynetic_test_guard$
DECLARE
    v_database text := current_database();
BEGIN
    IF v_database NOT IN ('fulfilment_dev', 'fulfilment_test') THEN
        RAISE EXCEPTION
            'SAFETY STOP: database test execution is forbidden against database "%". Only fulfilment_dev and fulfilment_test are allowed.',
            v_database;
    END IF;

    RAISE NOTICE 'SAFETY: test database verified as %', v_database;
END
$dynetic_test_guard$;
-- DYNETIC_TEST_ENVIRONMENT_GUARD_END
BEGIN;

INSERT INTO core.CLIENT (CLIENT_ID,DESCRIPTION,ACTIVE) VALUES ('WHEDGE','Warehouse Edge Test',true)
ON CONFLICT (CLIENT_ID) DO NOTHING;
INSERT INTO core.SKU (CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES ('WHEDGE','EDGE-SKU','Warehouse edge SKU','N','N','N','N','N')
ON CONFLICT (CLIENT_ID,SKU_ID) DO NOTHING;
INSERT INTO core.LOCATION (LOCATION_ID,LOC_TYPE,LOCK_STATUS,VOLUME,COUNT_NEEDED,ID,DESCRIPTION,ACTIVE,LIVESTOCK_ALLOWED,DISALLOW_ALLOC)
VALUES ('WH-EDGE-LOC','STORAGE','UNLOCKED',100,'N',920001,'Warehouse edge loc','Y','Y','N')
ON CONFLICT (LOCATION_ID) DO NOTHING;
INSERT INTO core.INVENTORY (CLIENT_ID,SKU_ID,LOCATION_ID,QTY_ON_HAND,QTY_ALLOCATED,LOCK_STATUS,RECEIPT_DSTAMP,MOVE_DSTAMP,DISALLOW_ALLOC,DESCRIPTION)
VALUES ('WHEDGE','EDGE-SKU','WH-EDGE-LOC',10,0,'UNLOCKED',now()-interval '5 days',now(),'N','WH edge stock');

-- Short pick 2 of 5, release 3, then reallocate and finish remaining 3.
INSERT INTO core.ORDER_HEADER (CLIENT_ID,ORDER_ID,ORDER_DATE,FREE_DELIVERY,FULFILMENT_STATUS) VALUES ('WHEDGE','EDGE-ORDER-1',now(),'N','NEW');
INSERT INTO core.ORDER_LINE (CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES ('WHEDGE','EDGE-ORDER-1',1,'EDGE-SKU',5,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('WHEDGE','EDGE-ORDER-1');
SELECT * FROM core.CREATE_PICK_TASKS('WHEDGE','EDGE-ORDER-1','TEST');
DO $$
DECLARE v_task BIGINT; v_status VARCHAR;
BEGIN
    SELECT PICK_TASK_ID INTO v_task FROM core.PICK_TASK WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-1';
    SELECT RESULT_STATUS INTO v_status FROM core.CONFIRM_PICK(v_task,2,'TEST','STATION',true,'Only two found');
    IF v_status<>'SHORT' THEN RAISE EXCEPTION 'Edge test: expected SHORT, got %',v_status; END IF;
    IF (SELECT QTY_PICKED FROM core.ORDER_LINE WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-1' AND LINE_ID=1)<>2 THEN RAISE EXCEPTION 'Edge test: picked should be 2'; END IF;
    IF (SELECT QTY_SOFT_ALLOCATED FROM core.ORDER_LINE WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-1' AND LINE_ID=1)<>0 THEN RAISE EXCEPTION 'Edge test: soft allocation should be zero after short close'; END IF;
END
$$;
SELECT * FROM core.ALLOCATE_ORDER('WHEDGE','EDGE-ORDER-1');
SELECT * FROM core.CREATE_PICK_TASKS('WHEDGE','EDGE-ORDER-1','TEST');
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT PICK_TASK_ID,QTY_REQUIRED-QTY_PICKED-SHORT_QTY AS REMAINING FROM core.PICK_TASK
             WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-1' AND STATUS IN ('OPEN','PART_PICKED')
    LOOP
        PERFORM * FROM core.CONFIRM_PICK(r.PICK_TASK_ID,r.REMAINING,'TEST','STATION',false,NULL);
    END LOOP;
    IF (SELECT QTY_PICKED FROM core.ORDER_LINE WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-1' AND LINE_ID=1)<>5 THEN
        RAISE EXCEPTION 'Edge test: reallocation should allow order to reach 5 picked';
    END IF;
END
$$;

-- Over-pick must be rejected without changing inventory.
INSERT INTO core.ORDER_HEADER (CLIENT_ID,ORDER_ID,ORDER_DATE,FREE_DELIVERY,FULFILMENT_STATUS) VALUES ('WHEDGE','EDGE-ORDER-2',now(),'N','NEW');
INSERT INTO core.ORDER_LINE (CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES ('WHEDGE','EDGE-ORDER-2',1,'EDGE-SKU',2,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('WHEDGE','EDGE-ORDER-2');
SELECT * FROM core.CREATE_PICK_TASKS('WHEDGE','EDGE-ORDER-2','TEST');
DO $$
DECLARE v_task BIGINT; v_status VARCHAR;
BEGIN
    SELECT PICK_TASK_ID INTO v_task FROM core.PICK_TASK WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-2';
    SELECT RESULT_STATUS INTO v_status FROM core.CONFIRM_PICK(v_task,3,'TEST','STATION',false,NULL);
    IF v_status<>'ERROR' THEN RAISE EXCEPTION 'Edge test: over-pick should return ERROR'; END IF;
END
$$;

-- Deallocation after task creation must cancel task, release stock, retain history.
INSERT INTO core.ORDER_HEADER (CLIENT_ID,ORDER_ID,ORDER_DATE,FREE_DELIVERY,FULFILMENT_STATUS) VALUES ('WHEDGE','EDGE-ORDER-3',now(),'N','NEW');
INSERT INTO core.ORDER_LINE (CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES ('WHEDGE','EDGE-ORDER-3',1,'EDGE-SKU',1,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('WHEDGE','EDGE-ORDER-3');
SELECT * FROM core.CREATE_PICK_TASKS('WHEDGE','EDGE-ORDER-3','TEST');
SELECT * FROM core.DEALLOCATE_ORDER('WHEDGE','EDGE-ORDER-3');
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM core.PICK_TASK WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-3' AND STATUS<>'CANCELLED') THEN
        RAISE EXCEPTION 'Edge test: deallocated unpicked task should be CANCELLED';
    END IF;
    IF EXISTS (SELECT 1 FROM core.ALLOCATION WHERE CLIENT_ID='WHEDGE' AND ORDER_ID='EDGE-ORDER-3' AND (QTY_ALLOCATED-QTY_PICKED-QTY_RELEASED)<>0) THEN
        RAISE EXCEPTION 'Edge test: deallocated allocation still open';
    END IF;
END
$$;

-- Competing orders cannot reserve more than physical stock remaining.
-- At this point order 1 consumed 5 physically; 5 remain. Order 2 has 2 reserved.
INSERT INTO core.ORDER_HEADER (CLIENT_ID,ORDER_ID,ORDER_DATE,FREE_DELIVERY,FULFILMENT_STATUS) VALUES ('WHEDGE','EDGE-ORDER-4',now(),'N','NEW');
INSERT INTO core.ORDER_LINE (CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES ('WHEDGE','EDGE-ORDER-4',1,'EDGE-SKU',5,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('WHEDGE','EDGE-ORDER-4');
DO $$
DECLARE v_onhand NUMERIC; v_alloc NUMERIC;
BEGIN
    SELECT SUM(QTY_ON_HAND),SUM(QTY_ALLOCATED) INTO v_onhand,v_alloc FROM core.INVENTORY WHERE CLIENT_ID='WHEDGE' AND SKU_ID='EDGE-SKU';
    IF v_alloc>v_onhand THEN RAISE EXCEPTION 'Edge test: reserved % exceeds on-hand %',v_alloc,v_onhand; END IF;
    IF EXISTS (SELECT 1 FROM core.INVENTORY_RESERVATION_RECONCILIATION WHERE CLIENT_ID='WHEDGE' AND RECONCILIATION_STATUS<>'OK') THEN
        RAISE EXCEPTION 'Edge test: reservation reconciliation mismatch';
    END IF;
END
$$;

ROLLBACK;
\echo 'Warehouse execution edge-case tests passed.'
