\set ON_ERROR_STOP on
BEGIN;

INSERT INTO core.CLIENT (CLIENT_ID,DESCRIPTION,ACTIVE)
VALUES ('CARRTEST','Carrier Test',TRUE)
ON CONFLICT (CLIENT_ID) DO NOTHING;

INSERT INTO core.SKU (
    CLIENT_ID,SKU_ID,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,
    AFFILIATE_FALLBACK,COMING_SOON,EACH_WEIGHT,EACH_VOLUME
) VALUES
    ('CARRTEST','CARR-SKU','N','N','N','N','N',2.000,2000)
ON CONFLICT (CLIENT_ID,SKU_ID) DO NOTHING;

-- Carrier smoke test must be self-contained. Do not depend on a LOCATION
-- created by another test because all earlier tests run inside BEGIN/ROLLBACK.
INSERT INTO core.LOCATION (
    LOCATION_ID,
    LOC_TYPE,
    LOCK_STATUS,
    VOLUME,
    DISALLOW_ALLOC,
    COUNT_NEEDED,
    ID,
    DESCRIPTION,
    ACTIVE,
    LIVESTOCK_ALLOWED
)
VALUES (
    'CARR-TEST-LOC',
    'STORAGE',
    'UNLOCKED',
    1000000,
    'N',
    'N',
    990001,
    'Carrier selection smoke-test location',
    'Y',
    'Y'
)
ON CONFLICT (LOCATION_ID) DO NOTHING;

INSERT INTO core.ORDER_HEADER (
    CLIENT_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,INV_CURRENCY,
    FREE_DELIVERY,COUNTRY,POSTCODE,FULFILMENT_STATUS
) VALUES
    ('CARRTEST','CARR-ORDER-1',now(),100,'GBP','N','GB','CV13 0AA','READY_TO_SHIP');

INSERT INTO core.ORDER_LINE (
    CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_PICKED,QTY_SHIPPED
) VALUES
    ('CARRTEST','CARR-ORDER-1',1,'CARR-SKU',1,1,0);

INSERT INTO core.ORDER_CONTAINER (
    CLIENT_ID,ORDER_ID,CONTAINER_ID,STATUS,WEIGHT,VOLUME,DELIVERY_CLASS
) VALUES
    ('CARRTEST','CARR-ORDER-1','CARR-BOX-1','PACKED',2.000,2000,'STANDARD');

INSERT INTO core.SHIPPING_MANIFEST (
    CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,CONTAINER_ID,LOCATION_ID,
    QTY_PICKED,PICKED_DSTAMP,QTY_SHIPPED,SHIPPED,STATUS
)
VALUES (
    'CARRTEST','CARR-ORDER-1',1,'CARR-SKU','CARR-BOX-1','CARR-TEST-LOC',
    1,now(),0,'N','PACKED'
);

INSERT INTO config.CARRIER (CLIENT_ID,CARRIER_ID,DESCRIPTION,ACTIVE)
VALUES
    ('CARRTEST','CHEAP_A','Cheap carrier A',TRUE),
    ('CARRTEST','EXPENSIVE_B','Expensive carrier B',TRUE);

INSERT INTO config.CARRIER_SERVICE (
    CLIENT_ID,CARRIER_ID,SERVICE_LEVEL,DESCRIPTION,ACTIVE,
    MAX_WEIGHT_KG,BASE_COST,COST_PER_KG,LIVE_GOODS_ALLOWED,SORT_SEQUENCE
) VALUES
    ('CARRTEST','CHEAP_A','STANDARD','Standard',TRUE,15,3.00,0,FALSE,10),
    ('CARRTEST','EXPENSIVE_B','STANDARD','Standard',TRUE,15,7.00,0,FALSE,20);

SELECT *
FROM core.SELECT_CARRIER(
    'CARRTEST',
    'CARR-BOX-1',
    'STANDARD',
    'CHEAPEST',
    'TEST'
);

DO $$
DECLARE
    v RECORD;
BEGIN
    SELECT *
    INTO v
    FROM core.ORDER_CONTAINER
    WHERE CLIENT_ID='CARRTEST'
      AND CONTAINER_ID='CARR-BOX-1';

    IF v.CARRIER_ID <> 'CHEAP_A'
       OR v.SERVICE_LEVEL <> 'STANDARD'
       OR v.CARRIER_COST <> 3.00
    THEN
        RAISE EXCEPTION
            'Expected CHEAP_A at 3.00, got % / % / %',
            v.CARRIER_ID,
            v.SERVICE_LEVEL,
            v.CARRIER_COST;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM core.SHIPPING_MANIFEST
        WHERE CLIENT_ID='CARRTEST'
          AND CONTAINER_ID='CARR-BOX-1'
          AND CARRIER_ID='CHEAP_A'
          AND SERVICE_LEVEL='STANDARD'
    ) THEN
        RAISE EXCEPTION
            'Selected carrier was not propagated to SHIPPING_MANIFEST.';
    END IF;
END
$$;

ROLLBACK;
