\set ON_ERROR_STOP on

-- DYNETIC_TEST_ENVIRONMENT_GUARD_BEGIN
DO $dynetic_test_guard$
DECLARE
    v_database text := current_database();
BEGIN
    IF v_database NOT IN ('fulfilment_dev', 'fulfilment_test') THEN
        RAISE EXCEPTION
            'SAFETY STOP: database test execution is forbidden against database "%". Only fulfilment_dev and fulfilment_test are allowed.',
            v_database;
    END IF;

    RAISE NOTICE 'SAFETY: test database verified as %', v_database;
END
$dynetic_test_guard$;
-- DYNETIC_TEST_ENVIRONMENT_GUARD_END
BEGIN;

INSERT INTO core.CLIENT (CLIENT_ID,DESCRIPTION,ACTIVE)
VALUES ('CARREDGE','Carrier Edge',TRUE)
ON CONFLICT (CLIENT_ID) DO NOTHING;

INSERT INTO core.SKU (
    CLIENT_ID,SKU_ID,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON,EACH_WEIGHT,EACH_VOLUME
) VALUES
    ('CARREDGE','EDGE-SKU','N','N','N','N','N',5.000,5000)
ON CONFLICT (CLIENT_ID,SKU_ID) DO NOTHING;

INSERT INTO core.ORDER_HEADER (
    CLIENT_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,INV_CURRENCY,FREE_DELIVERY,COUNTRY,POSTCODE,FULFILMENT_STATUS
) VALUES
    ('CARREDGE','EDGE-ORDER-1',now(),250,'GBP','N','GB','CV13 1AA','READY_TO_SHIP');

INSERT INTO core.ORDER_LINE (
    CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_PICKED,QTY_SHIPPED
) VALUES
    ('CARREDGE','EDGE-ORDER-1',1,'EDGE-SKU',1,1,0);

INSERT INTO core.ORDER_CONTAINER (
    CLIENT_ID,ORDER_ID,CONTAINER_ID,STATUS,WEIGHT,VOLUME,DELIVERY_CLASS
) VALUES
    ('CARREDGE','EDGE-ORDER-1','EDGE-BOX-1','PACKED',5.000,5000,'LIVESTOCK');

INSERT INTO config.CARRIER (CLIENT_ID,CARRIER_ID,DESCRIPTION,ACTIVE)
VALUES
    ('CARREDGE','DRY_CHEAP','Dry only',TRUE),
    ('CARREDGE','LIVE_OK','Live approved',TRUE);

INSERT INTO config.CARRIER_SERVICE (
    CLIENT_ID,CARRIER_ID,SERVICE_LEVEL,DESCRIPTION,ACTIVE,MAX_WEIGHT_KG,BASE_COST,COST_PER_KG,LIVE_GOODS_ALLOWED,SORT_SEQUENCE
) VALUES
    ('CARREDGE','DRY_CHEAP','NEXTDAY','Cheap dry',TRUE,15,2.00,0,FALSE,10),
    ('CARREDGE','LIVE_OK','LIVE_NEXTDAY','Live next day',TRUE,20,15.00,0,TRUE,20);

INSERT INTO config.CARRIER_SELECTION_RULE (
    CLIENT_ID,RULE_NAME,PRIORITY,ACTIVE,CARRIER_ID,SERVICE_LEVEL,DELIVERY_CLASS,STOP_ON_MATCH
) VALUES
    ('CARREDGE','Livestock must use approved live service',10,TRUE,'LIVE_OK','LIVE_NEXTDAY','LIVESTOCK',TRUE);

SELECT * FROM core.SELECT_CARRIER('CARREDGE','EDGE-BOX-1','LIVESTOCK','CHEAPEST','TEST');

DO $$
DECLARE
    v RECORD;
BEGIN
    SELECT * INTO v FROM core.ORDER_CONTAINER
    WHERE CLIENT_ID='CARREDGE' AND CONTAINER_ID='EDGE-BOX-1';

    IF v.CARRIER_ID <> 'LIVE_OK' THEN
        RAISE EXCEPTION 'Livestock should select LIVE_OK, got %',v.CARRIER_ID;
    END IF;
END
$$;

-- Manual override requires a reason.
DO $$
DECLARE
    v_status varchar;
BEGIN
    SELECT RESULT_STATUS INTO v_status
    FROM core.OVERRIDE_CARRIER('CARREDGE','EDGE-BOX-1','LIVE_OK','LIVE_NEXTDAY','', 'TEST');

    IF v_status <> 'ERROR' THEN
        RAISE EXCEPTION 'Blank override reason should be rejected.';
    END IF;
END
$$;

SELECT * FROM core.OVERRIDE_CARRIER(
    'CARREDGE','EDGE-BOX-1','LIVE_OK','LIVE_NEXTDAY','Operational decision','TEST'
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM core.ORDER_CONTAINER
        WHERE CLIENT_ID='CARREDGE' AND CONTAINER_ID='EDGE-BOX-1'
          AND CARRIER_SELECTION_SOURCE='MANUAL_OVERRIDE'
          AND CARRIER_OVERRIDE_REASON='Operational decision'
    ) THEN
        RAISE EXCEPTION 'Manual override was not recorded.';
    END IF;
END
$$;

ROLLBACK;
