\set ON_ERROR_STOP on

-- DYNETIC_TEST_ENVIRONMENT_GUARD_BEGIN
DO $dynetic_test_guard$
DECLARE
    v_database text := current_database();
BEGIN
    IF v_database NOT IN ('fulfilment_dev', 'fulfilment_test') THEN
        RAISE EXCEPTION
            'SAFETY STOP: database test execution is forbidden against database "%". Only fulfilment_dev and fulfilment_test are allowed.',
            v_database;
    END IF;

    RAISE NOTICE 'SAFETY: test database verified as %', v_database;
END
$dynetic_test_guard$;
-- DYNETIC_TEST_ENVIRONMENT_GUARD_END
BEGIN;
-- DYNETIC 0.3.18 TEST SITE CONTRACT
INSERT INTO core.SITE (SITE_ID,DESCRIPTION,SITE_TYPE,TIME_ZONE,ACTIVE)
VALUES ('REGTEST','Regression Test Site','FULFILMENT','Europe/London',true)
ON CONFLICT (SITE_ID)
DO UPDATE SET ACTIVE=true,LAST_UPDATED_DSTAMP=now();


INSERT INTO core.CLIENT (CLIENT_ID,DESCRIPTION,ACTIVE)
VALUES ('MERGETEST','Merge Test',TRUE)
ON CONFLICT (CLIENT_ID) DO NOTHING;
-- DYNETIC 0.3.18 CLIENT-SITE MAP AFTER CLIENT INSERT
INSERT INTO config.CLIENT_SITE (CLIENT_ID,SITE_ID,ACTIVE,DEFAULT_FULFILMENT)
SELECT CLIENT_ID,'REGTEST',true,true
  FROM core.CLIENT
 WHERE ACTIVE=true
   AND CLIENT_ID NOT IN (
       SELECT CLIENT_ID
         FROM config.CLIENT_SITE
        WHERE ACTIVE=true
   )
ON CONFLICT (CLIENT_ID,SITE_ID)
DO UPDATE
   SET ACTIVE=true,
       DEFAULT_FULFILMENT=true,
       LAST_UPDATE_DSTAMP=now();


INSERT INTO core.ORDER_HEADER (CLIENT_ID, SITE_ID, ORDER_ID, ORDER_DATE, ORDER_VALUE, INV_CURRENCY, FREE_DELIVERY, FULFILMENT_PREFERENCE)
VALUES ('MERGETEST', (SELECT cs.SITE_ID FROM config.CLIENT_SITE cs WHERE cs.CLIENT_ID='MERGETEST' AND cs.ACTIVE=true ORDER BY cs.DEFAULT_FULFILMENT DESC, cs.SITE_ID LIMIT 1), 'MERGE-ORDER-1', now(), 30, 'GBP', 'N', 'CONSOLIDATE');

INSERT INTO core.ORDER_CONTAINER (
    CLIENT_ID,ORDER_ID,CONTAINER_ID,STATUS,WEIGHT,VOLUME,
    DELIVERY_CLASS,FULFILMENT_METHOD,HOLD_STATUS
)
VALUES
    ('MERGETEST','MERGE-ORDER-1','MERGE-A','PACKED',1,1000,
     'STANDARD','CARRIER','NONE'),
    ('MERGETEST','MERGE-ORDER-1','MERGE-B','PACKED',2,2000,
     'STANDARD','CARRIER','NONE');

DO $$
DECLARE
    v_allowed BOOLEAN;
BEGIN
    SELECT RESULT_ALLOWED
    INTO v_allowed
    FROM core.EVALUATE_CONTAINER_MERGE(
        'MERGETEST','MERGE-A','MERGE-B'
    );

    IF NOT v_allowed THEN
        RAISE EXCEPTION
            'Compatible same-class containers should be mergeable by safe default.';
    END IF;
END
$$;

SELECT *
FROM core.MERGE_CONTAINERS(
    'MERGETEST','MERGE-A','MERGE-B','TEST'
);

DO $$
DECLARE
    v RECORD;
BEGIN
    SELECT * INTO v
    FROM core.ORDER_CONTAINER
    WHERE CLIENT_ID='MERGETEST'
      AND CONTAINER_ID='MERGE-A';

    IF v.WEIGHT<>3 OR v.VOLUME<>3000 THEN
        RAISE EXCEPTION
            'Target totals are wrong: weight %, volume %',
            v.WEIGHT,v.VOLUME;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM core.ORDER_CONTAINER
        WHERE CLIENT_ID='MERGETEST'
          AND CONTAINER_ID='MERGE-B'
          AND STATUS='MERGED'
          AND MERGED_INTO_CONTAINER_ID='MERGE-A'
    ) THEN
        RAISE EXCEPTION
            'Source container was not marked MERGED.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM audit.RULE_DECISION_LOG
        WHERE CLIENT_ID='MERGETEST'
          AND ENGINE_NAME='CONTAINER_MERGE'
          AND ENTITY_ID='MERGE-B'
          AND DECISION='MERGED'
    ) THEN
        RAISE EXCEPTION
            'Successful merge was not audited.';
    END IF;
END
$$;

ROLLBACK;
