\set ON_ERROR_STOP on
\pset pager off
BEGIN;
INSERT INTO core.CLIENT(CLIENT_ID,DESCRIPTION,ACTIVE) VALUES('REGIF','Regression Interface',true) ON CONFLICT DO NOTHING;
INSERT INTO core.SKU(CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES('REGIF','REG-SKU','Regression SKU','N','N','N','N','N') ON CONFLICT DO NOTHING;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID,SOURCE_SYSTEM,SOURCE_ORDER_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,CURRENCY)
 VALUES('REGIF','TEST','NO-LINES','REG-NOLINES',now(),10,'GBP') RETURNING INTERFACE_ID INTO iid;
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%NO_ORDER_LINES%' THEN RAISE EXCEPTION 'No-lines validation failed: %',r; END IF;
 IF EXISTS(SELECT 1 FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF' AND ORDER_ID='REG-NOLINES') THEN RAISE EXCEPTION 'Invalid no-lines order reached core'; END IF;
END $$;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID,SOURCE_SYSTEM,SOURCE_ORDER_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,CURRENCY)
 VALUES('REGIF','TEST','BAD-QTY','REG-BADQTY',now(),10,'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'REG-SKU',0,10);
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%INVALID_QTY%' THEN RAISE EXCEPTION 'Invalid qty validation failed: %',r; END IF;
END $$;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID,SOURCE_SYSTEM,SOURCE_ORDER_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,CURRENCY)
 VALUES('REGIF','TEST','BAD-SKU','REG-BADSKU',now(),10,'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'DOES-NOT-EXIST',1,10);
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%SKU_NOT_FOUND%' THEN RAISE EXCEPTION 'Unknown SKU validation failed: %',r; END IF;
END $$;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID,SOURCE_SYSTEM,SOURCE_ORDER_ID,ORDER_ID,ORDER_DATE,ORDER_VALUE,CURRENCY)
 VALUES('REGIF','WEBSITE','IDEM-001','REG-IDEM',now(),10,'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'REG-SKU',1,10);
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid); IF r.RESULT_STATUS<>'PROCESSED' THEN RAISE EXCEPTION 'Initial interface process failed'; END IF;
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid); IF r.RESULT_STATUS<>'PROCESSED' THEN RAISE EXCEPTION 'Interface replay failed'; END IF;
 IF (SELECT COUNT(*) FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF' AND ORDER_ID='REG-IDEM')<>1 THEN RAISE EXCEPTION 'Duplicate core order created'; END IF;
 IF (SELECT ORDER_SOURCE FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF' AND ORDER_ID='REG-IDEM')<>'W' THEN RAISE EXCEPTION 'Website source mapping regressed'; END IF;
END $$;
ROLLBACK;
\echo 'Order interface negative/idempotency regression tests passed.'
