\set ON_ERROR_STOP on

-- DYNETIC_TEST_ENVIRONMENT_GUARD_BEGIN
DO $dynetic_test_guard$
DECLARE
    v_database text := current_database();
BEGIN
    IF v_database NOT IN ('fulfilment_dev', 'fulfilment_test') THEN
        RAISE EXCEPTION
            'SAFETY STOP: database test execution is forbidden against database "%". Only fulfilment_dev and fulfilment_test are allowed.',
            v_database;
    END IF;

    RAISE NOTICE 'SAFETY: test database verified as %', v_database;
END
$dynetic_test_guard$;
-- DYNETIC_TEST_ENVIRONMENT_GUARD_END
\pset pager off
BEGIN;
-- DYNETIC 0.3.18.2 AUTHORITATIVE ORDER-ID TEST CONTRACT
-- DYNETIC 0.3.18 TEST SITE CONTRACT
INSERT INTO core.SITE (SITE_ID,DESCRIPTION,SITE_TYPE,TIME_ZONE,ACTIVE)
VALUES ('REGTEST','Regression Test Site','FULFILMENT','Europe/London',true)
ON CONFLICT (SITE_ID)
DO UPDATE SET ACTIVE=true,LAST_UPDATED_DSTAMP=now();

INSERT INTO core.CLIENT(CLIENT_ID,DESCRIPTION,ACTIVE) VALUES('REGIF','Regression Interface',true) ON CONFLICT DO NOTHING;
-- DYNETIC 0.3.18 CLIENT-SITE MAP AFTER CLIENT INSERT
INSERT INTO config.CLIENT_SITE (CLIENT_ID,SITE_ID,ACTIVE,DEFAULT_FULFILMENT)
SELECT CLIENT_ID,'REGTEST',true,true
  FROM core.CLIENT
 WHERE ACTIVE=true
   AND CLIENT_ID NOT IN (
       SELECT CLIENT_ID
         FROM config.CLIENT_SITE
        WHERE ACTIVE=true
   )
ON CONFLICT (CLIENT_ID,SITE_ID)
DO UPDATE
   SET ACTIVE=true,
       DEFAULT_FULFILMENT=true,
       LAST_UPDATE_DSTAMP=now();

INSERT INTO core.SKU(CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES('REGIF','REG-SKU','Regression SKU','N','N','N','N','N') ON CONFLICT DO NOTHING;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID, SITE_ID, SOURCE_SYSTEM, SOURCE_ORDER_ID, ORDER_DATE, ORDER_VALUE, CURRENCY)
 VALUES('REGIF', (SELECT cs.SITE_ID FROM config.CLIENT_SITE cs WHERE cs.CLIENT_ID='REGIF' AND cs.ACTIVE=true ORDER BY cs.DEFAULT_FULFILMENT DESC, cs.SITE_ID LIMIT 1), 'TEST', 'NO-LINES', now(), 10, 'GBP') RETURNING INTERFACE_ID INTO iid;
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%NO_ORDER_LINES%' THEN RAISE EXCEPTION 'No-lines validation failed: %',r; END IF;
 IF EXISTS(SELECT 1 FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF') THEN RAISE EXCEPTION 'Invalid no-lines order reached core'; END IF;
END $$;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID, SITE_ID, SOURCE_SYSTEM, SOURCE_ORDER_ID, ORDER_DATE, ORDER_VALUE, CURRENCY)
 VALUES('REGIF', (SELECT cs.SITE_ID FROM config.CLIENT_SITE cs WHERE cs.CLIENT_ID='REGIF' AND cs.ACTIVE=true ORDER BY cs.DEFAULT_FULFILMENT DESC, cs.SITE_ID LIMIT 1), 'TEST', 'BAD-QTY', now(), 10, 'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'REG-SKU',0,10);
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%INVALID_QTY%' THEN RAISE EXCEPTION 'Invalid qty validation failed: %',r; END IF;
END $$;

DO $$ DECLARE iid uuid; r record; BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID, SITE_ID, SOURCE_SYSTEM, SOURCE_ORDER_ID, ORDER_DATE, ORDER_VALUE, CURRENCY)
 VALUES('REGIF', (SELECT cs.SITE_ID FROM config.CLIENT_SITE cs WHERE cs.CLIENT_ID='REGIF' AND cs.ACTIVE=true ORDER BY cs.DEFAULT_FULFILMENT DESC, cs.SITE_ID LIMIT 1), 'TEST', 'BAD-SKU', now(), 10, 'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'DOES-NOT-EXIST',1,10);
 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'ERROR' OR r.RESULT_MESSAGE NOT LIKE '%SKU_NOT_FOUND%' THEN RAISE EXCEPTION 'Unknown SKU validation failed: %',r; END IF;
END $$;

DO $$
DECLARE
 iid uuid;
 r record;
 v_order_id varchar(20);
BEGIN
 INSERT INTO interface.ORDER_HEADER_IF(CLIENT_ID, SITE_ID, SOURCE_SYSTEM, SOURCE_ORDER_ID, ORDER_DATE, ORDER_VALUE, CURRENCY)
 VALUES('REGIF', (SELECT cs.SITE_ID FROM config.CLIENT_SITE cs WHERE cs.CLIENT_ID='REGIF' AND cs.ACTIVE=true ORDER BY cs.DEFAULT_FULFILMENT DESC, cs.SITE_ID LIMIT 1), 'WEBSITE', 'IDEM-001', now(), 10, 'GBP') RETURNING INTERFACE_ID INTO iid;
 INSERT INTO interface.ORDER_LINE_IF(INTERFACE_ID,LINE_ID,SKU_ID,QTY_ORDERED,PRODUCT_PRICE) VALUES(iid,1,'REG-SKU',1,10);

 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'PROCESSED' OR r.RESULT_ORDER_ID IS NULL THEN
  RAISE EXCEPTION 'Initial interface process failed: %', r;
 END IF;
 v_order_id := r.RESULT_ORDER_ID;

 SELECT * INTO r FROM interface.PROCESS_ORDER_INTERFACE(iid);
 IF r.RESULT_STATUS<>'PROCESSED' THEN
  RAISE EXCEPTION 'Interface replay failed: %', r;
 END IF;
 IF r.RESULT_ORDER_ID IS DISTINCT FROM v_order_id THEN
  RAISE EXCEPTION 'Interface replay returned a different WMS order ID: % / %', v_order_id, r.RESULT_ORDER_ID;
 END IF;

 IF (SELECT COUNT(*) FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF' AND ORDER_ID=v_order_id)<>1 THEN
  RAISE EXCEPTION 'Duplicate core order created';
 END IF;
 IF (SELECT ORDER_SOURCE FROM core.ORDER_HEADER WHERE CLIENT_ID='REGIF' AND ORDER_ID=v_order_id)<>'W' THEN
  RAISE EXCEPTION 'Website source mapping regressed';
 END IF;
 IF (SELECT ORDER_ID FROM interface.ORDER_HEADER_IF WHERE INTERFACE_ID=iid) IS DISTINCT FROM v_order_id THEN
  RAISE EXCEPTION 'Interface header did not retain generated WMS order ID';
 END IF;
END $$;
ROLLBACK;
\echo 'Order interface negative/idempotency regression tests passed.'
