\set ON_ERROR_STOP on
\pset pager off
BEGIN;
INSERT INTO core.CLIENT(CLIENT_ID,DESCRIPTION,ACTIVE) VALUES('REGINV','Inventory Regression',true) ON CONFLICT DO NOTHING;
INSERT INTO core.SKU(CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES('REGINV','REG-INV-SKU','Inventory Regression SKU','N','N','N','N','N') ON CONFLICT DO NOTHING;
INSERT INTO core.LOCATION(LOCATION_ID,LOC_TYPE,LOCK_STATUS,VOLUME,COUNT_NEEDED,ID,DESCRIPTION,ACTIVE,LIVESTOCK_ALLOWED,DISALLOW_ALLOC)
VALUES('REG-INV-LOC','STORAGE','UNLOCKED',100,'N',993001,'Regression inventory','Y','Y','N') ON CONFLICT DO NOTHING;
INSERT INTO core.INVENTORY(CLIENT_ID,SKU_ID,LOCATION_ID,QTY_ON_HAND,QTY_ALLOCATED,LOCK_STATUS,RECEIPT_DSTAMP,MOVE_DSTAMP,DISALLOW_ALLOC)
VALUES('REGINV','REG-INV-SKU','REG-INV-LOC',10,0,'UNLOCKED',now()-interval '1 day',now(),'N');
INSERT INTO core.ORDER_HEADER(CLIENT_ID,ORDER_ID,ORDER_DATE,FREE_DELIVERY,FULFILMENT_STATUS) VALUES('REGINV','REG-INV-ORDER',now(),'N','NEW');
INSERT INTO core.ORDER_LINE(CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES('REGINV','REG-INV-ORDER',1,'REG-INV-SKU',4,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('REGINV','REG-INV-ORDER');
DO $$ BEGIN
 IF (SELECT QTY_ON_HAND FROM core.INVENTORY WHERE CLIENT_ID='REGINV' AND SKU_ID='REG-INV-SKU')<>10 THEN RAISE EXCEPTION 'Allocation changed physical stock'; END IF;
 IF (SELECT QTY_ALLOCATED FROM core.INVENTORY WHERE CLIENT_ID='REGINV' AND SKU_ID='REG-INV-SKU')<>4 THEN RAISE EXCEPTION 'Expected inventory allocation 4'; END IF;
 IF EXISTS(SELECT 1 FROM core.INVENTORY_RESERVATION_RECONCILIATION WHERE CLIENT_ID='REGINV' AND RECONCILIATION_STATUS<>'OK') THEN RAISE EXCEPTION 'Reconciliation mismatch after allocation'; END IF;
END $$;
SELECT * FROM core.CREATE_PICK_TASKS('REGINV','REG-INV-ORDER','REGTEST');
DO $$ DECLARE tid bigint; r record; BEGIN
 SELECT PICK_TASK_ID INTO tid FROM core.PICK_TASK WHERE CLIENT_ID='REGINV' AND ORDER_ID='REG-INV-ORDER';
 SELECT * INTO r FROM core.CONFIRM_PICK(tid,4,'REGTEST','REGTEST',false,NULL);
 IF r.RESULT_STATUS<>'PICKED' THEN RAISE EXCEPTION 'Pick failed: %',r; END IF;
 IF (SELECT QTY_ON_HAND FROM core.INVENTORY WHERE CLIENT_ID='REGINV' AND SKU_ID='REG-INV-SKU')<>6 THEN RAISE EXCEPTION 'Physical stock should be 6 after pick'; END IF;
 IF (SELECT QTY_ALLOCATED FROM core.INVENTORY WHERE CLIENT_ID='REGINV' AND SKU_ID='REG-INV-SKU')<>0 THEN RAISE EXCEPTION 'Reservation should be zero after pick'; END IF;
 IF (SELECT COALESCE(SUM(UPDATE_QTY),0) FROM core.INVENTORY_TRANSACTION WHERE CLIENT_ID='REGINV' AND REFERENCE_ID='REG-INV-ORDER' AND CODE='PICK')<>-4 THEN RAISE EXCEPTION 'Inventory transaction does not reconcile to pick'; END IF;
END $$;
SELECT * FROM core.PACK_ORDER('REGINV','REG-INV-ORDER','REG-CONT-1','REGTEST','REGTEST');
SELECT * FROM core.SHIP_CONTAINER('REGINV','REG-CONT-1','REGTEST','REGTEST');
DO $$ BEGIN
 IF (SELECT QTY_ON_HAND FROM core.INVENTORY WHERE CLIENT_ID='REGINV' AND SKU_ID='REG-INV-SKU')<>6 THEN RAISE EXCEPTION 'Shipping reduced inventory a second time'; END IF;
 IF (SELECT QTY_SHIPPED FROM core.ORDER_LINE WHERE CLIENT_ID='REGINV' AND ORDER_ID='REG-INV-ORDER' AND LINE_ID=1)<>4 THEN RAISE EXCEPTION 'Order line shipped qty incorrect'; END IF;
 IF (SELECT FULFILMENT_STATUS FROM core.ORDER_HEADER WHERE CLIENT_ID='REGINV' AND ORDER_ID='REG-INV-ORDER')<>'SHIPPED' THEN RAISE EXCEPTION 'Order not SHIPPED'; END IF;
 IF EXISTS(SELECT 1 FROM core.INVENTORY_RESERVATION_RECONCILIATION WHERE CLIENT_ID='REGINV' AND RECONCILIATION_STATUS<>'OK') THEN RAISE EXCEPTION 'Final reservation reconciliation mismatch'; END IF;
END $$;
ROLLBACK;
\echo 'Inventory/order lifecycle reconciliation regression tests passed.'
