\set ON_ERROR_STOP on
\pset pager off
BEGIN;
INSERT INTO core.CLIENT(CLIENT_ID,DESCRIPTION,ACTIVE) VALUES('REGPAY','Payment Regression',true) ON CONFLICT DO NOTHING;
INSERT INTO core.SKU(CLIENT_ID,SKU_ID,DESCRIPTION,WEB_ACTIVE,WEB_FEATURED,SUPPLIER_DIRECT_ENABLED,AFFILIATE_FALLBACK,COMING_SOON)
VALUES('REGPAY','REG-PAY-SKU','Payment Regression SKU','N','N','N','N','N') ON CONFLICT DO NOTHING;
INSERT INTO core.LOCATION(LOCATION_ID,LOC_TYPE,LOCK_STATUS,VOLUME,COUNT_NEEDED,ID,DESCRIPTION,ACTIVE,LIVESTOCK_ALLOWED,DISALLOW_ALLOC)
VALUES('REG-PAY-LOC','STORAGE','UNLOCKED',100,'N',993021,'Payment Regression','Y','Y','N') ON CONFLICT DO NOTHING;
INSERT INTO core.INVENTORY(CLIENT_ID,SKU_ID,LOCATION_ID,QTY_ON_HAND,QTY_ALLOCATED,LOCK_STATUS,RECEIPT_DSTAMP,MOVE_DSTAMP,DISALLOW_ALLOC)
VALUES('REGPAY','REG-PAY-SKU','REG-PAY-LOC',10,0,'UNLOCKED',now(),now(),'N');

-- Failed payment must cancel fulfilment and release stock.
INSERT INTO core.ORDER_HEADER(CLIENT_ID,ORDER_ID,ORDER_DATE,STATUS,FREE_DELIVERY,FULFILMENT_STATUS,PAYMENT_STATUS,ORDER_VALUE,INV_CURRENCY)
VALUES('REGPAY','REG-PAY-FAIL',now(),'PENDING_PAYMENT','N','RESERVED','PENDING',20,'GBP');
INSERT INTO core.ORDER_LINE(CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES('REGPAY','REG-PAY-FAIL',1,'REG-PAY-SKU',2,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('REGPAY','REG-PAY-FAIL');
DO $$ DECLARE p jsonb; pid uuid; e jsonb; BEGIN
 p:=api.CREATE_PAYMENT_REQUEST('REGPAY',NULL,'ORDER','REG-PAY-FAIL','STRIPE','REG-PAY-FAIL-IDEM'); pid:=(p->>'paymentId')::uuid;
 PERFORM api.SET_PAYMENT_PROVIDER_REFERENCE('REGPAY',pid,'pi_reg_fail','requires_payment_method');
 e:=api.PROCESS_PAYMENT_EVENT('REGPAY','STRIPE','evt_reg_fail','payment_intent.payment_failed','pi_reg_fail','{"providerStatus":"requires_payment_method","failureCode":"card_declined","failureText":"Regression decline"}'::jsonb);
 IF e->>'status'<>'FAILED' THEN RAISE EXCEPTION 'Failed payment event status incorrect: %',e; END IF;
 IF (SELECT PAYMENT_STATUS FROM core.ORDER_HEADER WHERE CLIENT_ID='REGPAY' AND ORDER_ID='REG-PAY-FAIL')<>'FAILED' THEN RAISE EXCEPTION 'Order payment status not FAILED'; END IF;
 IF (SELECT FULFILMENT_STATUS FROM core.ORDER_HEADER WHERE CLIENT_ID='REGPAY' AND ORDER_ID='REG-PAY-FAIL')<>'CANCELLED' THEN RAISE EXCEPTION 'Failed payment did not cancel fulfilment'; END IF;
 IF (SELECT QTY_ALLOCATED FROM core.INVENTORY WHERE CLIENT_ID='REGPAY' AND SKU_ID='REG-PAY-SKU')<>0 THEN RAISE EXCEPTION 'Failed payment did not release inventory'; END IF;
END $$;

-- Timed-out pending order must release stock.
INSERT INTO core.ORDER_HEADER(CLIENT_ID,ORDER_ID,ORDER_DATE,STATUS,FREE_DELIVERY,FULFILMENT_STATUS,PAYMENT_STATUS,PAYMENT_DUE_DSTAMP,ORDER_VALUE,INV_CURRENCY)
VALUES('REGPAY','REG-PAY-EXP',now(),'PENDING_PAYMENT','N','RESERVED','PENDING',now()-interval '1 minute',10,'GBP');
INSERT INTO core.ORDER_LINE(CLIENT_ID,ORDER_ID,LINE_ID,SKU_ID,QTY_ORDERED,QTY_SOFT_ALLOCATED,QTY_PICKED,QTY_SHIPPED,ALLOCATE)
VALUES('REGPAY','REG-PAY-EXP',1,'REG-PAY-SKU',1,0,0,0,'Y');
SELECT * FROM core.ALLOCATE_ORDER('REGPAY','REG-PAY-EXP');
DO $$ DECLARE j jsonb; BEGIN
 j:=api.EXPIRE_PENDING_PAYMENT_ORDERS('REGPAY',100);
 IF (j->>'expiredOrders')::int<>1 THEN RAISE EXCEPTION 'Expected one expired payment order: %',j; END IF;
 IF (SELECT STATUS FROM core.ORDER_HEADER WHERE CLIENT_ID='REGPAY' AND ORDER_ID='REG-PAY-EXP')<>'CANCELLED' THEN RAISE EXCEPTION 'Expired payment order not cancelled'; END IF;
 IF (SELECT QTY_ALLOCATED FROM core.INVENTORY WHERE CLIENT_ID='REGPAY' AND SKU_ID='REG-PAY-SKU')<>0 THEN RAISE EXCEPTION 'Expired payment order did not release inventory'; END IF;
END $$;
ROLLBACK;
\echo 'Payment failure/expiry regression tests passed.'
