CREATE TABLE IF NOT EXISTS config.ALLOCATION_RULE (
    RULE_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    RULE_NAME varchar(120) NOT NULL,
    PRIORITY integer NOT NULL DEFAULT 100,
    STRATEGY varchar(40) NOT NULL DEFAULT 'FIFO',
    ACTIVE boolean NOT NULL DEFAULT true,
    STOP_ON_MATCH boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now()
);
