CREATE TABLE IF NOT EXISTS config.CARRIER_SELECTION_CONDITION (
    CONDITION_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_ID bigint NOT NULL REFERENCES config.CARRIER_SELECTION_RULE(RULE_ID) ON DELETE CASCADE,
    FIELD_NAME varchar(80) NOT NULL,
    OPERATOR varchar(20) NOT NULL,
    VALUE_TEXT text,
    VALUE_NUMERIC numeric(18,6),
    VALUE_BOOLEAN boolean,
    VALUE_FROM numeric(18,6),
    VALUE_TO numeric(18,6),
    CONDITION_GROUP integer NOT NULL DEFAULT 1,
    SEQUENCE integer NOT NULL DEFAULT 100,
    NEGATE boolean NOT NULL DEFAULT false
);
