CREATE TABLE IF NOT EXISTS config.CARRIER_SERVICE_RATE (
    RATE_ID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID                VARCHAR(30) NOT NULL,
    CARRIER_ID               VARCHAR(30) NOT NULL,
    SERVICE_LEVEL            VARCHAR(50) NOT NULL,
    MIN_WEIGHT_KG            NUMERIC(12,3) NOT NULL DEFAULT 0,
    MAX_WEIGHT_KG            NUMERIC(12,3),
    POSTCODE_PREFIX          VARCHAR(20),
    COUNTRY_CODE             VARCHAR(3),
    BASE_COST                NUMERIC(12,2) NOT NULL DEFAULT 0,
    COST_PER_KG              NUMERIC(12,4) NOT NULL DEFAULT 0,
    SURCHARGE                NUMERIC(12,2) NOT NULL DEFAULT 0,
    ACTIVE                   BOOLEAN NOT NULL DEFAULT TRUE,
    PRIORITY                 INTEGER NOT NULL DEFAULT 100,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    CREATED_DSTAMP           TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP      TIMESTAMPTZ NOT NULL DEFAULT now(),

    FOREIGN KEY (CLIENT_ID, CARRIER_ID, SERVICE_LEVEL)
        REFERENCES config.CARRIER_SERVICE (CLIENT_ID, CARRIER_ID, SERVICE_LEVEL),

    CONSTRAINT CK_CARRIER_SERVICE_RATE_WEIGHT
        CHECK (MIN_WEIGHT_KG >= 0 AND (MAX_WEIGHT_KG IS NULL OR MAX_WEIGHT_KG >= MIN_WEIGHT_KG)),

    CONSTRAINT CK_CARRIER_SERVICE_RATE_COST
        CHECK (BASE_COST >= 0 AND COST_PER_KG >= 0 AND SURCHARGE >= 0)
);

COMMENT ON TABLE config.CARRIER_SERVICE_RATE IS
'Optional weight/postcode/country rate bands used by Carrier Selection V1. A separate table is justified because one carrier service can have many commercial rate bands.';
