CREATE TABLE IF NOT EXISTS config.DELIVERY_CLASS_CONTROL (
    CLIENT_ID VARCHAR(30) NOT NULL,
    DELIVERY_CLASS VARCHAR(30) NOT NULL,
    CARRIER_DESPATCH_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    HOLD_REASON VARCHAR(250),
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, DELIVERY_CLASS),
    CONSTRAINT FK_DELIVERY_CLASS_CONTROL_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID)
);

COMMENT ON TABLE config.DELIVERY_CLASS_CONTROL IS
'Client-specific despatch control by generic delivery class. Used to stop carrier despatch for a class without stopping order creation, picking, packing, collection or local delivery.';
