CREATE TABLE IF NOT EXISTS config.FEATURE_FLAG (
    CLIENT_ID varchar(30) NOT NULL REFERENCES core.CLIENT(CLIENT_ID),
    FEATURE_KEY varchar(100) NOT NULL,
    ENABLED boolean NOT NULL DEFAULT false,
    DESCRIPTION varchar(250),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (CLIENT_ID, FEATURE_KEY)
);
