CREATE TABLE IF NOT EXISTS config.MERGE_RULE_CONDITION (
    CONDITION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_ID BIGINT NOT NULL,
    FIELD_NAME VARCHAR(50) NOT NULL,
    OPERATOR VARCHAR(20) NOT NULL,
    VALUE_TEXT VARCHAR(250),
    VALUE_NUMERIC NUMERIC(18,4),
    VALUE_BOOLEAN BOOLEAN,
    VALUE_FROM NUMERIC(18,4),
    VALUE_TO NUMERIC(18,4),
    CONDITION_GROUP INTEGER NOT NULL DEFAULT 1,
    SEQUENCE INTEGER NOT NULL DEFAULT 10,
    NEGATE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT FK_MERGE_CONDITION_RULE
        FOREIGN KEY (RULE_ID)
        REFERENCES config.MERGE_RULE (RULE_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE config.MERGE_RULE_CONDITION IS
'Safe, structured conditions for MERGE_RULE. Conditions inside a group are ANDed; groups are ORed.';
