CREATE TABLE IF NOT EXISTS config.MERGE_RULE (
    RULE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID VARCHAR(30) NOT NULL,
    RULE_NAME VARCHAR(100) NOT NULL,
    PRIORITY INTEGER NOT NULL DEFAULT 100,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DECISION VARCHAR(10) NOT NULL DEFAULT 'ALLOW',
    STOP_ON_MATCH BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_UPDATE_DSTAMP TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT FK_MERGE_RULE_CLIENT
        FOREIGN KEY (CLIENT_ID)
        REFERENCES core.CLIENT (CLIENT_ID),
    CONSTRAINT CK_MERGE_RULE_DECISION
        CHECK (DECISION IN ('ALLOW','DENY')),
    CONSTRAINT UQ_MERGE_RULE_NAME
        UNIQUE (CLIENT_ID, RULE_NAME)
);

COMMENT ON TABLE config.MERGE_RULE IS
'Ordered, client-specific rules controlling whether two compatible containers may be consolidated.';
