CREATE TABLE IF NOT EXISTS config.SYSTEM_SETTING (
    SETTING_ID bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID varchar(30) REFERENCES core.CLIENT(CLIENT_ID),
    SITE_ID varchar(30),
    SETTING_KEY varchar(100) NOT NULL,
    VALUE_TEXT text,
    VALUE_NUMERIC numeric(18,6),
    VALUE_BOOLEAN boolean,
    DESCRIPTION varchar(250),
    ACTIVE boolean NOT NULL DEFAULT true,
    CREATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    LAST_UPDATED_DSTAMP timestamptz NOT NULL DEFAULT now(),
    UNIQUE (CLIENT_ID, SITE_ID, SETTING_KEY)
);
