CREATE OR REPLACE VIEW api.CATALOG_VARIANT_AVAILABILITY AS
SELECT
    pv.CLIENT_ID,
    pv.PRODUCT_ID,
    pv.SKU_ID,
    pv.VARIANT_NAME,
    pv.OPTION_VALUES,
    pv.WEB_PRICE,
    pv.COMPARE_AT_PRICE,
    pv.ACTIVE,
    COALESCE(SUM(
        CASE
            WHEN COALESCE(i.DISALLOW_ALLOC,'N') <> 'Y'
             AND COALESCE(l.DISALLOW_ALLOC,'N') <> 'Y'
             AND COALESCE(l.ACTIVE,'Y') = 'Y'
            THEN GREATEST(COALESCE(i.QTY_ON_HAND,0)-COALESCE(i.QTY_ALLOCATED,0),0)
            ELSE 0
        END
    ),0) AS AVAILABLE_QTY
FROM core.PRODUCT_VARIANT pv
LEFT JOIN core.INVENTORY i
  ON i.CLIENT_ID=pv.CLIENT_ID
 AND i.SKU_ID=pv.SKU_ID
LEFT JOIN core.LOCATION l
  ON l.LOCATION_ID=i.LOCATION_ID
GROUP BY
    pv.CLIENT_ID,
    pv.PRODUCT_ID,
    pv.SKU_ID,
    pv.VARIANT_NAME,
    pv.OPTION_VALUES,
    pv.WEB_PRICE,
    pv.COMPARE_AT_PRICE,
    pv.ACTIVE;
