CREATE OR REPLACE VIEW api.CATALOG_VARIANT_AVAILABILITY AS
SELECT
    -- IMPORTANT:
    -- Existing V1 columns must remain in the same order for CREATE OR REPLACE VIEW.
    pv.CLIENT_ID,
    pv.PRODUCT_ID,
    pv.SKU_ID,
    pv.VARIANT_NAME,
    pv.OPTION_VALUES,
    pv.WEB_PRICE,
    pv.COMPARE_AT_PRICE,
    pv.ACTIVE,
    CASE
      WHEN pv.AVAILABILITY_STATE='AVAILABLE' THEN COALESCE(SUM(
        CASE
            WHEN COALESCE(i.DISALLOW_ALLOC,'N') <> 'Y'
             AND UPPER(COALESCE(i.LOCK_STATUS,'')) NOT IN ('LOCKED','HOLD','QUARANTINE')
             AND COALESCE(l.DISALLOW_ALLOC,'N') <> 'Y'
             AND UPPER(COALESCE(l.LOCK_STATUS,'')) NOT IN ('LOCKED','HOLD','QUARANTINE')
             AND COALESCE(l.ACTIVE,'Y') = 'Y'
            THEN GREATEST(COALESCE(i.QTY_ON_HAND,0)-COALESCE(i.QTY_ALLOCATED,0),0)
            ELSE 0
        END
      ),0)
      ELSE 0
    END AS AVAILABLE_QTY,

    -- V2 columns are appended after all V1 columns.
    pv.SALE_TYPE,
    pv.AVAILABILITY_STATE,
    pv.EXPECTED_AVAILABLE_FROM,
    pv.EXPECTED_AVAILABLE_TO,
    pv.WEB_METADATA,
    pv.MIN_ORDER_QTY,
    pv.MAX_ORDER_QTY,
    pv.QTY_INCREMENT
FROM core.PRODUCT_VARIANT pv
LEFT JOIN core.INVENTORY i
  ON i.CLIENT_ID=pv.CLIENT_ID
 AND i.SKU_ID=pv.SKU_ID
LEFT JOIN core.LOCATION l
  ON l.LOCATION_ID=i.LOCATION_ID
GROUP BY
    pv.CLIENT_ID,
    pv.PRODUCT_ID,
    pv.SKU_ID,
    pv.VARIANT_NAME,
    pv.OPTION_VALUES,
    pv.WEB_PRICE,
    pv.COMPARE_AT_PRICE,
    pv.ACTIVE,
    pv.SALE_TYPE,
    pv.AVAILABILITY_STATE,
    pv.EXPECTED_AVAILABLE_FROM,
    pv.EXPECTED_AVAILABLE_TO,
    pv.WEB_METADATA,
    pv.MIN_ORDER_QTY,
    pv.MAX_ORDER_QTY,
    pv.QTY_INCREMENT;
