CREATE OR REPLACE VIEW api.CATALOG_PRODUCT_LIST AS
SELECT
    p.CLIENT_ID,
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.SLUG,
    p.BRAND_NAME,
    p.CATEGORY_CODE,
    c.CATEGORY_NAME,
    c.SLUG AS CATEGORY_SLUG,
    p.SHORT_DESCRIPTION,
    p.DELIVERY_CLASS,
    p.CURRENCY,
    p.MEDIA,
    p.FEATURED,
    p.SORT_SEQUENCE,
    MIN(v.WEB_PRICE) FILTER (WHERE v.ACTIVE) AS FROM_PRICE,
    MAX(v.WEB_PRICE) FILTER (WHERE v.ACTIVE) AS TO_PRICE,
    COALESCE(SUM(v.AVAILABLE_QTY) FILTER (WHERE v.ACTIVE),0) AS AVAILABLE_QTY
FROM core.PRODUCT p
LEFT JOIN core.PRODUCT_CATEGORY c
  ON c.CLIENT_ID=p.CLIENT_ID
 AND c.CATEGORY_CODE=p.CATEGORY_CODE
LEFT JOIN api.CATALOG_VARIANT_AVAILABILITY v
  ON v.CLIENT_ID=p.CLIENT_ID
 AND v.PRODUCT_ID=p.PRODUCT_ID
WHERE p.ACTIVE=TRUE
GROUP BY
    p.CLIENT_ID,p.PRODUCT_ID,p.PRODUCT_NAME,p.SLUG,p.BRAND_NAME,
    p.CATEGORY_CODE,c.CATEGORY_NAME,c.SLUG,p.SHORT_DESCRIPTION,
    p.DELIVERY_CLASS,p.CURRENCY,p.MEDIA,p.FEATURED,p.SORT_SEQUENCE;
