CREATE OR REPLACE FUNCTION api.EXPIRE_STOCK_RESERVATIONS(p_client_id VARCHAR)
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v RECORD; n INTEGER:=0;
BEGIN
 FOR v IN SELECT RESERVATION_ID FROM core.STOCK_RESERVATION WHERE CLIENT_ID=p_client_id AND STATUS='ACTIVE' AND EXPIRES_DSTAMP<=now() FOR UPDATE SKIP LOCKED LOOP
   PERFORM api.RELEASE_STOCK_RESERVATION(p_client_id,v.RESERVATION_ID,'EXPIRED'); n:=n+1;
 END LOOP;
 RETURN n;
END; $$;
