CREATE OR REPLACE FUNCTION api.GET_ACCOUNT_RESERVATIONS(p_client_id VARCHAR,p_account_id UUID)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
SELECT COALESCE(jsonb_agg(api.GET_STOCK_RESERVATION(r.CLIENT_ID,r.RESERVATION_ID)
    ORDER BY r.CREATED_DSTAMP DESC),'[]'::jsonb)
FROM core.STOCK_RESERVATION r
WHERE r.CLIENT_ID=p_client_id AND r.ACCOUNT_ID=p_account_id;
$$;
