CREATE OR REPLACE FUNCTION api.GET_INTEREST_CONTACTS(p_client_id VARCHAR,p_sku_id VARCHAR)
RETURNS JSONB LANGUAGE sql STABLE AS $$
SELECT COALESCE(jsonb_agg(jsonb_build_object('interestId',INTEREST_ID,'type',INTEREST_TYPE,'requestedQty',REQUESTED_QTY,'name',CONTACT_NAME,'email',EMAIL,'phone',PHONE,'preferredChannel',PREFERRED_CHANNEL,'createdAt',CREATED_DSTAMP) ORDER BY CREATED_DSTAMP),'[]'::jsonb)
FROM core.CUSTOMER_INTEREST WHERE CLIENT_ID=p_client_id AND SKU_ID=p_sku_id AND STATUS='ACTIVE' AND CONSENT_TO_NOTIFY=TRUE;
$$;
