CREATE OR REPLACE FUNCTION api.GET_INTEREST_SUMMARY(p_client_id VARCHAR,p_sku_id VARCHAR)
RETURNS JSONB LANGUAGE sql STABLE AS $$
SELECT jsonb_build_object(
 'skuId',p_sku_id,
 'activeCount',COUNT(*) FILTER(WHERE STATUS='ACTIVE'),
 'requestedQty',COALESCE(SUM(REQUESTED_QTY) FILTER(WHERE STATUS='ACTIVE'),0),
 'byType',jsonb_build_object(
   'waitlist',COUNT(*) FILTER(WHERE STATUS='ACTIVE' AND INTEREST_TYPE='WAITLIST'),
   'growingStock',COUNT(*) FILTER(WHERE STATUS='ACTIVE' AND INTEREST_TYPE='GROWING_STOCK')
 ))
FROM core.CUSTOMER_INTEREST WHERE CLIENT_ID=p_client_id AND SKU_ID=p_sku_id;
$$;
