CREATE OR REPLACE FUNCTION api.GET_AFFILIATE_DEMAND(p_client_id VARCHAR,p_from TIMESTAMPTZ DEFAULT NULL,p_to TIMESTAMPTZ DEFAULT NULL)
RETURNS JSONB LANGUAGE sql STABLE AS $$
SELECT COALESCE(jsonb_agg(jsonb_build_object('productId',x.PRODUCT_ID,'productName',x.PRODUCT_NAME,'merchant',x.MERCHANT_NAME,'clicks',x.CLICKS) ORDER BY x.CLICKS DESC),'[]'::jsonb)
FROM (SELECT l.PRODUCT_ID,p.PRODUCT_NAME,l.MERCHANT_NAME,COUNT(*) CLICKS FROM audit.AFFILIATE_CLICK c JOIN core.PRODUCT_AFFILIATE_LINK l ON l.LINK_ID=c.LINK_ID JOIN core.PRODUCT p ON p.CLIENT_ID=l.CLIENT_ID AND p.PRODUCT_ID=l.PRODUCT_ID WHERE c.CLIENT_ID=p_client_id AND (p_from IS NULL OR c.CREATED_DSTAMP>=p_from) AND (p_to IS NULL OR c.CREATED_DSTAMP<p_to) GROUP BY l.PRODUCT_ID,p.PRODUCT_NAME,l.MERCHANT_NAME) x;
$$;
