CREATE OR REPLACE FUNCTION api.GET_AFFILIATE_LINKS(p_client_id VARCHAR,p_slug VARCHAR)
RETURNS JSONB LANGUAGE sql STABLE AS $$
SELECT COALESCE(jsonb_agg(jsonb_build_object('linkId',a.LINK_ID,'skuId',a.SKU_ID,'merchant',a.MERCHANT_NAME,'campaignCode',a.CAMPAIGN_CODE) ORDER BY a.SORT_SEQUENCE),'[]'::jsonb)
FROM core.PRODUCT_AFFILIATE_LINK a JOIN core.PRODUCT p ON p.CLIENT_ID=a.CLIENT_ID AND p.PRODUCT_ID=a.PRODUCT_ID
WHERE p.CLIENT_ID=p_client_id AND p.SLUG=p_slug AND p.ACTIVE=TRUE AND a.ACTIVE=TRUE;
$$;
