CREATE OR REPLACE FUNCTION api.GET_GIFT_CARD_BALANCE(p_client_id VARCHAR,p_code VARCHAR)
RETURNS JSONB LANGUAGE sql STABLE AS $$
SELECT jsonb_build_object('valid',STATUS='ACTIVE' AND (EXPIRES_DSTAMP IS NULL OR EXPIRES_DSTAMP>now()),'currency',CURRENCY,'balance',BALANCE,'status',STATUS,'expiresAt',EXPIRES_DSTAMP)
FROM core.GIFT_CARD WHERE CLIENT_ID=p_client_id AND UPPER(GIFT_CODE)=UPPER(TRIM(p_code));
$$;
