CREATE OR REPLACE FUNCTION api.MARK_INTEREST_NOTIFIED(p_client_id VARCHAR,p_interest_ids JSONB)
RETURNS INTEGER LANGUAGE plpgsql AS $$ DECLARE n INTEGER; BEGIN
 UPDATE core.CUSTOMER_INTEREST SET STATUS='NOTIFIED',NOTIFIED_DSTAMP=now(),LAST_UPDATE_DSTAMP=now()
 WHERE CLIENT_ID=p_client_id AND STATUS='ACTIVE' AND INTEREST_ID IN (SELECT value::uuid FROM jsonb_array_elements_text(COALESCE(p_interest_ids,'[]'::jsonb))); GET DIAGNOSTICS n=ROW_COUNT; RETURN n; END; $$;
