CREATE OR REPLACE FUNCTION api.MODERATE_PRODUCT_REVIEW(p_client_id VARCHAR,p_review_id UUID,p_decision VARCHAR)
RETURNS JSONB LANGUAGE plpgsql AS $$ DECLARE d VARCHAR:=UPPER(p_decision); BEGIN
 IF d NOT IN ('APPROVED','REJECTED') THEN RAISE EXCEPTION 'INVALID_REVIEW_DECISION'; END IF;
 UPDATE core.PRODUCT_REVIEW SET STATUS=d,PUBLISHED_DSTAMP=CASE WHEN d='APPROVED' THEN now() ELSE NULL END WHERE CLIENT_ID=p_client_id AND REVIEW_ID=p_review_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'REVIEW_NOT_FOUND'; END IF; RETURN jsonb_build_object('reviewId',p_review_id,'status',d); END; $$;
