CREATE OR REPLACE FUNCTION api.RELEASE_STOCK_RESERVATION(p_client_id VARCHAR,p_reservation_id UUID,p_status VARCHAR DEFAULT 'RELEASED')
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE v_status VARCHAR:=UPPER(COALESCE(p_status,'RELEASED'));
BEGIN
 IF v_status NOT IN ('RELEASED','EXPIRED','CANCELLED') THEN RAISE EXCEPTION 'INVALID_RELEASE_STATUS'; END IF;
 IF NOT EXISTS(SELECT 1 FROM core.STOCK_RESERVATION WHERE CLIENT_ID=p_client_id AND RESERVATION_ID=p_reservation_id AND STATUS='ACTIVE' FOR UPDATE) THEN
   RETURN api.GET_STOCK_RESERVATION(p_client_id,p_reservation_id);
 END IF;
 UPDATE core.INVENTORY i SET QTY_ALLOCATED=GREATEST(COALESCE(i.QTY_ALLOCATED,0)-x.qty,0)
 FROM (SELECT ri.INVENTORY_KEY,SUM(ri.QTY_RESERVED) qty FROM core.STOCK_RESERVATION_INVENTORY ri JOIN core.STOCK_RESERVATION_LINE rl ON rl.RESERVATION_LINE_ID=ri.RESERVATION_LINE_ID WHERE rl.RESERVATION_ID=p_reservation_id GROUP BY ri.INVENTORY_KEY) x
 WHERE i.KEY=x.INVENTORY_KEY;
 UPDATE core.STOCK_RESERVATION SET STATUS=v_status,LAST_UPDATE_DSTAMP=now() WHERE CLIENT_ID=p_client_id AND RESERVATION_ID=p_reservation_id;
 RETURN api.GET_STOCK_RESERVATION(p_client_id,p_reservation_id);
END; $$;
