CREATE OR REPLACE FUNCTION api.SEARCH_CATALOG(
 p_client_id VARCHAR,p_query VARCHAR DEFAULT NULL,p_category_slug VARCHAR DEFAULT NULL,
 p_availability_state VARCHAR DEFAULT NULL,p_sale_type VARCHAR DEFAULT NULL
) RETURNS JSONB LANGUAGE sql STABLE AS $$
WITH matched AS (
 SELECT p.CLIENT_ID,p.PRODUCT_ID,p.PRODUCT_NAME,p.SLUG,p.BRAND_NAME,p.PRODUCT_TYPE,
        p.CATEGORY_CODE,c.CATEGORY_NAME,c.SLUG CATEGORY_SLUG,p.SHORT_DESCRIPTION,p.DELIVERY_CLASS,p.CURRENCY,
        p.FEATURED,p.SORT_SEQUENCE,
        MIN(v.WEB_PRICE) FILTER(WHERE v.ACTIVE) FROM_PRICE,
        MAX(v.WEB_PRICE) FILTER(WHERE v.ACTIVE) TO_PRICE,
        COALESCE(SUM(v.AVAILABLE_QTY) FILTER(WHERE v.ACTIVE),0) AVAILABLE_QTY
 FROM core.PRODUCT p
 LEFT JOIN core.PRODUCT_CATEGORY c ON c.CLIENT_ID=p.CLIENT_ID AND c.CATEGORY_CODE=p.CATEGORY_CODE
 LEFT JOIN api.CATALOG_VARIANT_AVAILABILITY v ON v.CLIENT_ID=p.CLIENT_ID AND v.PRODUCT_ID=p.PRODUCT_ID
 WHERE p.CLIENT_ID=p_client_id AND p.ACTIVE=TRUE
   AND (p_category_slug IS NULL OR c.SLUG=p_category_slug)
   AND (p_availability_state IS NULL OR EXISTS(SELECT 1 FROM api.CATALOG_VARIANT_AVAILABILITY vx WHERE vx.CLIENT_ID=p.CLIENT_ID AND vx.PRODUCT_ID=p.PRODUCT_ID AND vx.ACTIVE=TRUE AND vx.AVAILABILITY_STATE=UPPER(p_availability_state)))
   AND (p_sale_type IS NULL OR EXISTS(SELECT 1 FROM api.CATALOG_VARIANT_AVAILABILITY vx WHERE vx.CLIENT_ID=p.CLIENT_ID AND vx.PRODUCT_ID=p.PRODUCT_ID AND vx.ACTIVE=TRUE AND vx.SALE_TYPE=UPPER(p_sale_type)))
   AND (NULLIF(TRIM(p_query),'') IS NULL OR p.PRODUCT_NAME ILIKE '%'||p_query||'%' OR COALESCE(p.BRAND_NAME,'') ILIKE '%'||p_query||'%' OR COALESCE(p.SHORT_DESCRIPTION,'') ILIKE '%'||p_query||'%' OR p.SPECIFICATION::text ILIKE '%'||p_query||'%' OR p.SEARCH_METADATA::text ILIKE '%'||p_query||'%' OR EXISTS(SELECT 1 FROM core.PRODUCT_SEARCH_ALIAS a WHERE a.CLIENT_ID=p.CLIENT_ID AND a.PRODUCT_ID=p.PRODUCT_ID AND a.ACTIVE=TRUE AND a.ALIAS_TEXT ILIKE '%'||p_query||'%'))
 GROUP BY p.CLIENT_ID,p.PRODUCT_ID,p.PRODUCT_NAME,p.SLUG,p.BRAND_NAME,p.PRODUCT_TYPE,p.CATEGORY_CODE,c.CATEGORY_NAME,c.SLUG,p.SHORT_DESCRIPTION,p.DELIVERY_CLASS,p.CURRENCY,p.FEATURED,p.SORT_SEQUENCE
)
SELECT COALESCE(jsonb_agg(jsonb_build_object(
 'productId',PRODUCT_ID,'name',PRODUCT_NAME,'slug',SLUG,'brand',BRAND_NAME,'productType',PRODUCT_TYPE,
 'category',jsonb_build_object('code',CATEGORY_CODE,'name',CATEGORY_NAME,'slug',CATEGORY_SLUG),
 'shortDescription',SHORT_DESCRIPTION,'deliveryClass',DELIVERY_CLASS,'currency',CURRENCY,
 'fromPrice',FROM_PRICE,'toPrice',TO_PRICE,'availableQty',AVAILABLE_QTY,'featured',FEATURED
) ORDER BY SORT_SEQUENCE,PRODUCT_NAME),'[]'::jsonb) FROM matched;
$$;
