CREATE OR REPLACE FUNCTION api.SET_CONTACT_PREFERENCE(p_client_id VARCHAR,p_payload JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE v_id UUID; v_type VARCHAR; v_value TEXT; v_channel VARCHAR; v_purpose VARCHAR;
BEGIN
 v_type:=UPPER(COALESCE(NULLIF(TRIM(p_payload->>'contactType'),''),'EMAIL')); v_value:=LOWER(NULLIF(TRIM(p_payload->>'contactValue'),'')); v_channel:=UPPER(NULLIF(TRIM(p_payload->>'channel'),'')); v_purpose:=UPPER(NULLIF(TRIM(p_payload->>'purpose'),''));
 IF v_value IS NULL OR v_channel NOT IN ('EMAIL','SMS','WHATSAPP') OR v_purpose NOT IN ('MARKETING','STOCK_ALERT','TRANSACTIONAL') THEN RAISE EXCEPTION 'INVALID_CONTACT_PREFERENCE'; END IF;
 INSERT INTO core.CONTACT_PREFERENCE(CLIENT_ID,CUSTOMER_ID,CONTACT_TYPE,CONTACT_VALUE,CHANNEL,PURPOSE,OPTED_IN)
 VALUES(p_client_id,NULLIF(TRIM(p_payload->>'customerId'),''),v_type,v_value,v_channel,v_purpose,COALESCE((p_payload->>'optedIn')::boolean,FALSE))
 ON CONFLICT (CLIENT_ID,CONTACT_TYPE,CONTACT_VALUE,CHANNEL,PURPOSE) DO UPDATE SET OPTED_IN=EXCLUDED.OPTED_IN,CUSTOMER_ID=COALESCE(EXCLUDED.CUSTOMER_ID,core.CONTACT_PREFERENCE.CUSTOMER_ID),CONSENT_DSTAMP=now(),LAST_UPDATE_DSTAMP=now()
 RETURNING CONTACT_PREFERENCE_ID INTO v_id;
 RETURN jsonb_build_object('preferenceId',v_id,'saved',TRUE);
END; $$;
