CREATE OR REPLACE FUNCTION api.SUBMIT_RESERVED_WEB_ORDER(p_client_id VARCHAR,p_reservation_id UUID,p_payload JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE r core.STOCK_RESERVATION%ROWTYPE; v_payload JSONB; v_items JSONB; result JSONB; alloc RECORD;
BEGIN
 SELECT * INTO r FROM core.STOCK_RESERVATION WHERE CLIENT_ID=p_client_id AND RESERVATION_ID=p_reservation_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'RESERVATION_NOT_FOUND'; END IF;
 IF r.STATUS<>'ACTIVE' THEN RAISE EXCEPTION 'RESERVATION_NOT_ACTIVE'; END IF;
 IF r.EXPIRES_DSTAMP<=now() THEN PERFORM api.RELEASE_STOCK_RESERVATION(p_client_id,p_reservation_id,'EXPIRED'); RAISE EXCEPTION 'RESERVATION_EXPIRED'; END IF;
 IF LOWER(COALESCE(p_payload#>>'{customer,email}',''))<>LOWER(r.EMAIL) THEN RAISE EXCEPTION 'RESERVATION_EMAIL_MISMATCH'; END IF;
 SELECT jsonb_agg(jsonb_build_object('sku_id',SKU_ID,'qty',QTY_RESERVED) ORDER BY RESERVATION_LINE_ID) INTO v_items FROM core.STOCK_RESERVATION_LINE WHERE RESERVATION_ID=p_reservation_id;
 v_payload:=jsonb_set(p_payload,'{items}',COALESCE(v_items,'[]'::jsonb),TRUE);
 PERFORM api.RELEASE_STOCK_RESERVATION(p_client_id,p_reservation_id,'RELEASED');
 result:=api.SUBMIT_WEB_ORDER(p_client_id,v_payload);
 IF result->>'status'<>'ACCEPTED' THEN RAISE EXCEPTION 'RESERVED_ORDER_SUBMISSION_FAILED: %',result; END IF;
 SELECT * INTO alloc FROM core.ALLOCATE_ORDER(p_client_id,result->>'orderId');
 IF alloc.RESULT_STATUS NOT IN ('ALLOCATED','ALREADY_ALLOCATED') THEN RAISE EXCEPTION 'RESERVED_ORDER_ALLOCATION_FAILED: %',alloc.RESULT_MESSAGE; END IF;
 UPDATE core.STOCK_RESERVATION SET STATUS='CONVERTED',CONVERTED_ORDER_ID=result->>'orderId',LAST_UPDATE_DSTAMP=now() WHERE RESERVATION_ID=p_reservation_id;
 RETURN result||jsonb_build_object('reservationId',p_reservation_id,'reservationConverted',TRUE,'allocationStatus',alloc.RESULT_STATUS);
END; $$;
