CREATE OR REPLACE FUNCTION api.VALIDATE_PROMOTION(p_client_id VARCHAR,p_code VARCHAR,p_order_value NUMERIC,p_delivery_class VARCHAR DEFAULT NULL)
RETURNS JSONB LANGUAGE plpgsql STABLE AS $$
DECLARE p RECORD; d NUMERIC:=0;
BEGIN
 SELECT * INTO p FROM config.PROMOTION WHERE CLIENT_ID=p_client_id AND UPPER(PROMO_CODE)=UPPER(TRIM(p_code)) AND ACTIVE=TRUE AND (STARTS_DSTAMP IS NULL OR STARTS_DSTAMP<=now()) AND (ENDS_DSTAMP IS NULL OR ENDS_DSTAMP>=now());
 IF NOT FOUND THEN RETURN jsonb_build_object('valid',FALSE,'code','PROMO_NOT_FOUND'); END IF;
 IF p.MIN_ORDER_VALUE IS NOT NULL AND COALESCE(p_order_value,0)<p.MIN_ORDER_VALUE THEN RETURN jsonb_build_object('valid',FALSE,'code','MIN_ORDER_NOT_MET','minimum',p.MIN_ORDER_VALUE); END IF;
 IF p.DELIVERY_CLASS IS NOT NULL AND UPPER(COALESCE(p_delivery_class,''))<>UPPER(p.DELIVERY_CLASS) THEN RETURN jsonb_build_object('valid',FALSE,'code','DELIVERY_CLASS_NOT_ELIGIBLE'); END IF;
 IF p.PROMOTION_TYPE='PERCENT' THEN d:=ROUND(COALESCE(p_order_value,0)*(p.PROMOTION_VALUE/100.0),2); ELSIF p.PROMOTION_TYPE='FIXED' THEN d:=LEAST(COALESCE(p.PROMOTION_VALUE,0),COALESCE(p_order_value,0)); END IF;
 RETURN jsonb_build_object('valid',TRUE,'promotionId',p.PROMOTION_ID,'promoCode',p.PROMO_CODE,'type',p.PROMOTION_TYPE,'value',p.PROMOTION_VALUE,'discountAmount',d,'freeDelivery',p.PROMOTION_TYPE='FREE_DELIVERY');
END; $$;
